### ISSUE TITLE
一些小的问题希望能改善

### ISSUE THREAD

**Issue by yq2yizi** [AlexLiuSheng/CheckVersionLib#100]
1 内存泄漏比较严重 leaks发现的
2 点击下载后,点击重试,然后再点取消,然后点notification上面的重试,闪退原因是AllenChecker.getGlobalContext() = null
3 第二步修复之后,点击下载后,点击重试,然后再点取消,按home键到后台,点notification上面的重试整个界面不能点击,原因是有一层透明的activity,需要按两次返回键才能返回正确的界面
4 大佬加油!

**Comment by AlexLiuSheng** [comment]
是用V2版
