### ISSUE TITLE
希望作者提供一个设置通知栏图标的方法。多谢了

### ISSUE THREAD

**Issue by steven-gao** [AlexLiuSheng/CheckVersionLib#101]
按道理讲，通知栏和应用图标本该是2个图片，现在我用的一个图片，通知栏的图标显示为一个灰色的方块。所以希望作者提供一个设置通知栏图标的方法。多谢了。关于通知栏图标的设置有篇郭霖的文章，不知道对你是否有帮助  -----http://blog.csdn.net/guolin_blog/article/details/50945228

**Comment by AlexLiuSheng** [comment]
使用V2
