### ISSUE TITLE
V2版本 编译出错

### ISSUE THREAD

**Issue by ouyangshengduo** [AlexLiuSheng/CheckVersionLib#106]
V2版本使用编译SDK版本低于27，无法编译通过

部分error:
Error:(9, 5) error: resource android:attr/colorError not found.

**Comment by AlexLiuSheng** [comment]
你编译的sdk版本是多少

**Comment by ouyangshengduo** [comment]
![image](https://user-images.githubusercontent.com/8730414/35203497-6f0f1502-ff63-11e7-80fa-87403bf91491.png)

**Comment by AlexLiuSheng** [comment]
用26吧

**Comment by hxw319726** [comment]
不想依赖support库，可以加 exclude group: 'com.android.support'

**Comment by xchz** [comment]
@ouyangshengduo 你的头像有点骚啊 兄弟
