### ISSUE TITLE
检查更新接口，如果回调onRequestVersionSuccess成功，但是result不需要更新，会弹出更新的Dialog。

### ISSUE THREAD

**Issue by HeWenhui** [AlexLiuSheng/CheckVersionLib#108]
检查更新接口，如果回调onRequestVersionSuccess成功，result返回是最新版本，不需要更新，这时候如果onRequestVersionSuccess（String result），return null,不实例化UIData，在SerVice中还是会启动UIActiivty，弹出dialog。这个应该改进一下，判断UIData是否为Null。因为请求接口检查成功，如果需要更新，会在成功的回调返回地址。

**Comment by AlexLiuSheng** [comment]
疏忽了，大兄dei多谢
