### ISSUE TITLE
版本请求无法根据版本号决定是否弹出下载框。

### ISSUE THREAD

**Issue by AndroidDevelopersLiqingwen** [AlexLiuSheng/CheckVersionLib#109]
正常的版本更新流程是：
 先请求服务器数据->解析数据判断版本号和apk下载地址->升级
 但是使用 `AllenVersionChecker
                    .getInstance()
                    .requestVersion()
                    .setRequestUrl("https://www.baidu.com")
                    .request(new RequestVersionListener(){});`
 即使我的版本不需要更新的也会弹出dialog。

**Comment by AlexLiuSheng** [comment]
嗯嗯 2.0.1已经解决了
