### ISSUE TITLE
有个报空指针异常的，上线报的比较多

### ISSUE THREAD

**Issue by 18710891669** [AlexLiuSheng/CheckVersionLib#11]
Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference

com.allenliu.versionchecklib.AVersionService.onStartCommand(AVersionService.java:39)
![default](https://user-images.githubusercontent.com/15627485/28126893-716c043e-675d-11e7-94a5-8968f06238d9.png)

**Comment by AlexLiuSheng** [comment]
才看到谢谢指正

**Comment by 18710891669** [comment]
这个修复没

**Comment by AlexLiuSheng** [comment]
修复了

**Comment by 18710891669** [comment]
发布在1.0.6了吗？写的确实不错

**Comment by AlexLiuSheng** [comment]
是的 优化了代码 ，丰富demo使用

**Comment by 18710891669** [comment]
![default](https://user-images.githubusercontent.com/15627485/28462054-18268002-6e4c-11e7-8027-e392e69721a8.png)   关于最新版本1.0.6有个问题，为什么在startService()之前要调用stopService(...)方法呢？

**Comment by AlexLiuSheng** [comment]
因为是demo测试 所以保证每次测试前service都是关闭的
