### ISSUE TITLE
点击下载更新后报错

### ISSUE THREAD

**Issue by 617450941** [AlexLiuSheng/CheckVersionLib#118]
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.example.a61745-1/base.apk)

**Comment by AlexLiuSheng** [comment]
support版本
