### ISSUE TITLE
downloadOnly()模式也必须显示VersionRequest的对话框？

### ISSUE THREAD

**Issue by hero0812** [AlexLiuSheng/CheckVersionLib#124]

**Comment by hero0812** [comment]
private void downloadAPK() {
        if (builder.isSilentDownload()) {
            requestPermissionAndDownload();
        } else {
            showVersionDialog();
        }
    }

**Comment by AlexLiuSheng** [comment]
2.0.4多了一个参数，可以设置直接下载安装，不显示对话框
