### ISSUE TITLE
设置强制更新，下载完成之后也会调用强制更新取消下载的回调

### ISSUE THREAD

**Issue by chenrong1994** [AlexLiuSheng/CheckVersionLib#127]
设置强制更新取消下载回调，在取消下载回调中退出APP，可是点击下载，在下载完成之后也会回调这个方法，退出APP，希望能优化一下

**Comment by AlexLiuSheng** [comment]
这是一个逻辑问题，我理解的强制更新就是，必须要使用新版本，老版本不能使用了，所以下载完成之后弹出到安装界面后就会回调关闭整个APP

**Comment by Dawn2Yuan** [comment]
关闭APP后  下载的新的APK不自动安装啊

**Comment by Dawn2Yuan** [comment]
设置强制更新取消下载回调，在取消下载回调中退出APP，可是点击下载，在下载完成之后也会回调这个方法，退出APP，

下载的新的APP因为整个APP退出了  所以没办法自动安装。
