### ISSUE TITLE
自定义更新对话框，怎么对话框显示的好慢？

### ISSUE THREAD

**Issue by jyygithub** [AlexLiuSheng/CheckVersionLib#136]
自定义更新对话框，怎么对话框显示的好慢？版本数据接口请求结束好久才出现版本对话框。

**Comment by jyygithub** [comment]
自定义更新对话框，怎么对话框显示的好慢？版本数据接口请求结束好久才出现版本对话框。

**Comment by Jiiiiiin** [comment]
请检查自己的接口响应速度和自己发送请求的框架代码
