### ISSUE TITLE
根据服务端返回的结果来确定是否强制更新的问题

### ISSUE THREAD

**Issue by 9hongfeng9** [AlexLiuSheng/CheckVersionLib#138]
isForce默认false 根据请求服务端返回的数据后来确定是否需要强制更新，但是请求网络比较耗时，在服务端数据没回来前，if (isForce) {
            builder.setForceUpdateListener(new ForceUpdateListener() {
                @Override
                public void onShouldForceUpdate() {
                    
                }
            });
这段代码已经被执行，所以isForce总是false,就没法设置成为强制更新了~请问怎么解决这个问题啊~

**Comment by AlexLiuSheng** [comment]
把if判断放到监听里面

**Comment by veryyoung** [comment]
@AlexLiuSheng 我也遇到同样的问题了。
在生成 Builder 的时候就需要指定 RequestVersionListener，isForce 是从远端来的结果，在得到 isForce 的时候，Builder 还没生成，没法 setForceUpdateListener。

不好意思挖了这么久的 issue 出来，希望得到作者的解答。
