### ISSUE TITLE
如果能减少对okgo依赖，仅使用okHttp或HttpURLConnection来下载就更好了

### ISSUE THREAD

**Issue by wangkangmao** [AlexLiuSheng/CheckVersionLib#14]
如果能减少对okgo依赖，仅使用okHttp或HttpURLConnection来下载就更好了

**Comment by AlexLiuSheng** [comment]
好的

**Comment by AlexLiuSheng** [comment]
好的 我下一版使用httpurlconnection来

**Comment by Key-CN** [comment]
而且整个项目clone下来跑不了
Error:(30, 13) Failed to resolve: com.lzy.net:okgo:2.1.4
<a href="openFile:D:/Develop/AndroidStudioProjects/CheckVersionLib/library/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Key-CN** [comment]
你试下重新从github上clone一个，我手动compile了okgo:2.1.4的jar包也不行

**Comment by AlexLiuSheng** [comment]
我可以啊

**Comment by Key-CN** [comment]
终于帮你找到问题了，是因为你设置了代理，你传代码之前把gradle.properties里面的代理参数删掉，因为每个人的代理端口不一样，我SS用的是1080端口，你的是9090端口。所以导致了。项目构建不成功



mrkey.k@gmail.com
 
发件人： AllenLiu
发送时间： 2017-08-11 10:08
收件人： AlexLiuSheng/CheckVersionLib
抄送： 计奇良; Comment
主题： Re: [AlexLiuSheng/CheckVersionLib] 如果能减少对okgo依赖，仅使用okHttp或HttpURLConnection来下载就更好了 (#14)
我可以啊

**Comment by AlexLiuSheng** [comment]
好的🙏谢谢指正。我马上改下😂

**Comment by Key-CN** [comment]
还有一个更新的问题，需要改一个判断，你没发现后续版本更新仍旧调用的老版本APK吗？我试试能不能给pull代码，可以的话，你show diff看一下吧

**Comment by AlexLiuSheng** [comment]
最新版已经处理了这个问题了啊 你看看行不

**Comment by Key-CN** [comment]
ok，那我pull一下你的新代码看看

**Comment by AlexLiuSheng** [comment]
好的，现在可以手动设置是否强制重新下载apk.你帮我看看，安装成功之后，默认apk会自动删除的。你看看你那边行不

**Comment by Key-CN** [comment]
OK。我等下帮你测试下，其实判断本地包类型就可以了。你之前有个判断PackageInfo的，把报名和版本号判断进去就好了
if (info != null && getPackageName().equals(info.packageName) && getPackageManager().getPackageInfo(getPackageName(), 0).versionName.equals(info.versionName)) {
                    result = true;
                }

**Comment by AlexLiuSheng** [comment]
嗯嗯 👍

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.6.0'
移除了okgo使用okhttp替代
