### ISSUE TITLE
如果自定义下载路径,下载后会出现"解析包错误"的异常.

### ISSUE THREAD

**Issue by cizkey** [AlexLiuSheng/CheckVersionLib#155]
rt. 在安卓6.0 和 7.0 上测试都出现问题.  使用默认路径则无此问题.

**Comment by pdog18** [comment]
不是吧，默认路径居然是
`/storage/emulated/0/AllenVersionPath/`

**Comment by feimenggo** [comment]
你设置自定义下载路径要以“/”结尾

**Comment by AlexLiuSheng** [comment]
@cizkey @feimenggo 是的，这个需要注意一下
