### ISSUE TITLE
用户下载一遍了，安装的时候点取消，下次打开又要重新下载。

### ISSUE THREAD

**Issue by liwenxing3028** [AlexLiuSheng/CheckVersionLib#16]

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.0.8'

**Comment by liwenxing3028** [comment]
在未下载完成的时候，强行退出App ，下次打开App的时候 通知栏上正在下载，但是点升级按钮提示解析包失败。之后就狂报Service空指针，不知道是不是我的问题

**Comment by liwenxing3028** [comment]
在未下载完成的时候，强行退出App ，下次打开App的时候 通知栏上正在下载，但是点升级按钮提示解析包失败。之后就狂报Service空指针，不知道是不是我的问题

**Comment by AlexLiuSheng** [comment]
如果正常下载完毕 点击取消 下次不回继续下载了吧？你是自己集成还是用的demo。这个问题我要看下

**Comment by liwenxing3028** [comment]
第一次能正常下载（也能正常安装），但是点击取消，下次点击升级 提示APK解析失败，然后有两个按钮（取消，重新下载）不管点哪个按钮 都会继续下载，然后下载100%就崩了。 提示的是service空指针什么的。

**Comment by AlexLiuSheng** [comment]
好的 我正在修复

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.0.9' 应该可以了

**Comment by liwenxing3028** [comment]
ok
