### ISSUE TITLE
Unable to create service com.allenliu.versionchecklib.v2.ui.VersionService: org.greenrobot.eventbus.EventBusException: Subscriber class com.allenliu.versionchecklib.v2.ui.VersionService and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by hexianqiao3755** [AlexLiuSheng/CheckVersionLib#161]
Unable to create service com.allenliu.versionchecklib.v2.ui.VersionService: org.greenrobot.eventbus.EventBusException: Subscriber class com.allenliu.versionchecklib.v2.ui.VersionService and its super classes have no public methods with the @Subscribe annotation

打开后闪退, 这是错误信息

**Comment by hexianqiao3755** [comment]
这问题是真的坑,  解决版本把EventBus混淆掉
在proguard-rules.pro里新增混淆
-keepattributes *Annotation*
-keepclassmembers class * {    @org.greenrobot.eventbus.Subscribe <methods>;}
-keep enum org.greenrobot.eventbus.ThreadMode { *; } 
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {    <init>(java.lang.Throwable);}

**Comment by TWBfly** [comment]
首先感谢大佬开源！！！百度混淆EventBus，建议大佬在库中混淆升级更新下。
