### ISSUE TITLE
下载进度显示负数，数字应该是文件大小，通知栏进度一直是0%

### ISSUE THREAD

**Issue by luyun181** [AlexLiuSheng/CheckVersionLib#163]

**Comment by js215844742** [comment]
下载文件小的时候，没什么问题，文件大了就就出现你说的这种问题了，我自定义了下载中dialog布局，然后自己处理了progress，就ok了

**Comment by llsomeday** [comment]
在下载apk的后台设置文件大小就可以了，response.setContentLength((xxx);源码里面是取这个大小来设置文件大小，计算下载进度条的
