### ISSUE TITLE
dialog展示有延迟

### ISSUE THREAD

**Issue by hy20160705** [AlexLiuSheng/CheckVersionLib#170]
dialog有2~3秒的延迟 ，我没有去走网络请求，我认为原因之一是每次都要去创建dialog造成的 码主在哪里可以优化一下？ 还有我觉得这个框架定得太死了 不容易扩展（当然 只是我粗浅的认知，如有得罪还请多多包涵）
代码如下：
  uiData.setDownloadUrl(mVersionInfo.getLocalUrl());
        uiData.setContent(mVersionInfo.getDescription());
        uiData.setTitle(getResources().getString(R.string.app_version_update_tips_title));
        builder= AllenVersionChecker
                .getInstance().downloadOnly(
                        uiData
                );

        builder.setShowDownloadingDialog(false);
        builder.setCustomVersionDialogListener(new CustomVersionDialogListener() {
            @Override
            public Dialog getCustomVersionDialog(Context context, UIData versionBundle) {
                BaseDialog baseDialog = new BaseDialog(context, R.style.BaseDialog, R.layout.commom_update_pop);
                //versionBundle 就是UIData，之前开发者传入的，在这里可以拿出UI数据并展示
                return baseDialog;
            }
        }) ;
        builder.excuteMission(getContext());

**Comment by AlexLiuSheng** [comment]
感谢，这里你可以自己在实例化一个全局的dialog，不用再回调里面new
