### ISSUE TITLE
静默下载 点击不能调用,没反应

### ISSUE THREAD

**Issue by hongyancode** [AlexLiuSheng/CheckVersionLib#173]
public void a(View view) {
            //方法一  可以下载
//        AllenVersionChecker.getInstance().downloadOnly(UIData.create().setDownloadUrl(Conf.API_IV_PICASSO)).excuteMission(this);
        //方法二 无反应
        mDownloadBuilder = AllenVersionChecker.getInstance().downloadOnly(CreateUiData());
        //静默下载and 直接下载
        mDownloadBuilder.setSilentDownload(true); //默认false
//        如果本地有安装包缓存也会重新下载apk
        mDownloadBuilder.setForceRedownload(true); //默认false
        mDownloadBuilder.setDirectDownload(true);
        mDownloadBuilder.setShowNotification(false);
        mDownloadBuilder.setShowDownloadingDialog(false);
        mDownloadBuilder.setShowDownloadFailDialog(false);
    }
    /**
     * 设置 下载url
     * */
    private UIData CreateUiData() {
        UIData uiData = UIData.create();
        uiData.setDownloadUrl(Conf.API_IV_PICASSO);
        return uiData;
    }

**Comment by AlexLiuSheng** [comment]
excuteMission(this);
