### ISSUE TITLE
targetSdkVersion设置成28,引入2.0.6就报这个错

### ISSUE THREAD

**Issue by q296494327** [AlexLiuSheng/CheckVersionLib#174]
版本设置成28(报错):
 android = [
               compileSdkVersion       : 28,
               buildToolsVersion       : "28.0.2",
               minSdkVersion           : 16,
               targetSdkVersion        : 28,
               versionCode             : 1,
               versionName             : "1.0.0"
    ]

     version = [
                   androidSupportSdkVersion: "28.0.0-rc02",
	]

D:\java\gradle\.gradle\caches\transforms-1\files-1.1\library-2.0.6.aar\d3bb718d6b3814ee2a00dfb1480bf0b8\res\values\values.xml
Error:(6, 5) error: <item> inner element must either be a resource reference or empty.
Error:(7, 5) error: <item> inner element must either be a resource reference or empty.
Error:(8, 5) error: <item> inner element must either be a resource reference or empty.
Error:(9, 5) error: <item> inner element must either be a resource reference or empty.
Error:(10, 5) error: <item> inner element must either be a resource reference or empty.
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

设置成(成功编译):
android = [
               compileSdkVersion       : 26,
               buildToolsVersion       : "26.0.2",
               minSdkVersion           : 16,
               targetSdkVersion        : 26,
               versionCode             : 1,
               versionName             : "1.0.0"
    ]

version = [
                   androidSupportSdkVersion: "26.0.2",
	]

**Comment by AlexLiuSheng** [comment]
这个问题 我一直复现不了，你试试2.0.7 或者在自己的项目res/values里面加上这个看行不行
```
    <item name="versionchecklib_version_dialog_commit" type="id">0x1866</item>
    <item name="versionchecklib_failed_dialog_retry" type="id">0x1867</item>
    <item name="versionchecklib_failed_dialog_cancel" type="id">0x1868</item>
    <item name="versionchecklib_version_dialog_cancel" type="id">0x1869</item>
    <item name="versionchecklib_loading_dialog_cancel" type="id">0x1870</item>
```

**Comment by q296494327** [comment]
![image](https://user-images.githubusercontent.com/20579810/44982278-ef0ff600-afa7-11e8-8d88-2f61669098f8.png)
还是一样的,我再项目取名了一个ids.xml放了上面的内容,依然报错这个
是有两个地方报,都是这5个属性
异常显示的是:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

**Comment by AlexLiuSheng** [comment]
稍等好像找到解决办法了，你试试2.0.8

**Comment by q296494327** [comment]
作者厉害,现在编译通过了,可以了,是把0x1886这些都置空了呀
