### ISSUE TITLE
怎么取消cancel按钮

### ISSUE THREAD

**Issue by tmxd09887** [AlexLiuSheng/CheckVersionLib#175]
builder.setForceUpdateListener(() -> {
              forceUpdate();
          });

加了setForceUpdateListener，cancel就取消了，为什么不做成builder.setForceUpdate(true)来设置呢？

**Comment by AlexLiuSheng** [comment]
因为你需要在回调里面，手动关闭所有app，库做不到，如果你要取消cancelbutton 你可以自定义界面
