### ISSUE TITLE
创建弹出框崩溃

### ISSUE THREAD

**Issue by 3277076046** [AlexLiuSheng/CheckVersionLib#184]
#4102 java.lang.ClassNotFoundException
Didn't find class "android.support.v4.graphics.drawable.DrawableWrapper" on path: DexPathList[[zip file "/data/app/com.xx.xx.ess-oyEgZWqFDNmeMO3Y3ICj3g==/base.apk", zip file "/data/app/com.xx.xx.ess-oyEgZWqFDNmeMO3Y3ICj3g==/split_lib_dependencies_apk.apk", zip file "/data/app/com.xx.xx.ess-oyEgZWqFDNmeMO3Y3ICj3g==/split_lib_slice_0_apk.apk", zip file "/data/app/com.xx.xx.ess-oyEgZWqFDNmeMO3Y3ICj3g==/split_lib_slice_1_apk.apk", zip file "/data/app/com.xx

com.allenliu.versionchecklib.v2.ui.UIActivity.showDefaultDialog(UIActivity.java:92)

**Comment by AlexLiuSheng** [comment]
support版本
