### ISSUE TITLE
通知栏显示进度，进度条下方的进度数字：25%/100%能不能把百分号去掉？！或者直接显示：25%

### ISSUE THREAD

**Issue by zhiziqing** [AlexLiuSheng/CheckVersionLib#19]
通知栏显示进度，进度条下方的进度数字：25%/100%能不能把百分号去掉？！或者直接显示：25%

**Comment by AlexLiuSheng** [comment]
在你自己的项目里面重写    
<string name="versionchecklib_download_progress">下载进度:%d%%/100%%</string>
改成
<string name="versionchecklib_download_progress">下载进度:%d/100</string>
或者
<string name="versionchecklib_download_progress">下载进度::%d%%</string>

**Comment by AlexLiuSheng** [comment]
在你自己的项目里面重写
`<string name="versionchecklib_download_progress">下载进度:%d%%/100%%</string>`
改成
`<string name="versionchecklib_download_progress">下载进度:%d/100</string>`
或者
`<string name="versionchecklib_download_progress">下载进度:%d%%</string>`

**Comment by zhiziqing** [comment]
好的，谢谢
