### ISSUE TITLE
麻烦作者把设置apk名称的函数也暴露出来

### ISSUE THREAD

**Issue by hengxing0080** [AlexLiuSheng/CheckVersionLib#190]
公司不希望把包名当apk名称，想使用（应用简称+环境类型+versonName）规则来命名，希望DownloadBuilder有类似setApkName的函数来使用，有劳作者了

**Comment by AlexLiuSheng** [comment]
2.1.1 setApkName

**Comment by hengxing0080** [comment]
Thanks
