### ISSUE TITLE
假如有些版本需要强制更新，有些不需要

### ISSUE THREAD

**Issue by qdk0901** [AlexLiuSheng/CheckVersionLib#194]
按照文档中的提供的
            builder.setForceUpdateListener(new ForceUpdateListener() {
                @Override
                public void onShouldForceUpdate() {
                    finish();
                }
            });
好像实现不了啊，强制更新选项都是预先设置的，而不是根据服务器的返回可以动态设置的

**Comment by AlexLiuSheng** [comment]
你可以将服务器返回的数据或者UIData设为全局变量，然后在里面onShouldForceUpdate里面做判断

**Comment by Destiny01** [comment]
你这个强制更新是不是点击Dialog外部和点击返回键处理成一样的了，按理说只处理点击返回键，点击外部弹窗不消失就行。

**Comment by IurKwan** [comment]
升级提示框要根据是否强制升级显示取消按钮
如何实现

**Comment by AlexLiuSheng** [comment]
@IurKwan 自定义界面
