### ISSUE TITLE
Android4.3 引入CheckVersionLib1.0.1之后打开直接奔溃

### ISSUE THREAD

**Issue by ShannonCoek** [AlexLiuSheng/CheckVersionLib#2]
gradle配置：
compileSdkVersion 23
        buildToolsVersion '22.0.1'
minSdkVersion 18
        targetSdkVersion 23

引入库之后自动把我的support库更新到24，然后出现NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID
应用直接无法打开。请问有没有什么解决方案？
（在Android5.0的手机上打开没问题）

**Comment by AlexLiuSheng** [comment]
compileSdkVersion 
buildToolsVersion 
support包的版本最好统一 可以都改成24
