### ISSUE TITLE
控制强制更新只能在开始设置的时候吗？不能在请求了更新内容后根据更新内容控制是否强制更新？

### ISSUE THREAD

**Issue by wentaibao** [AlexLiuSheng/CheckVersionLib#20]

**Comment by AlexLiuSheng** [comment]
可以啊 你可以重写VersionDialogActivity 实现其中的onCancelClickListener 然后动态根据参数判断里面做的事 比如结束所有activity 具体的可以看demo 里面有详细说明

**Comment by AlexLiuSheng** [comment]
你可以在自定义的service里面判断了 ，可以查看最新的demo里的做法
