### ISSUE TITLE
我把build.gradle中的这些文件删除了 对项目的使用和打包用影响吗

### ISSUE THREAD

**Issue by hy20160705** [AlexLiuSheng/CheckVersionLib#202]
//def siteUrl = 'https://github.com/AlexLiuSheng/CheckVersionLib' // 项目的主页
//def gitUrl = 'https://github.com/AlexLiuSheng/CheckVersionLib.git' // Git仓库的url
//group = "com.allenliu.versionchecklib" // Maven Group ID for the artifact，一般填你唯一的包名
//install {
//    repositories.mavenInstaller {
//        // This generates POM.xml with proper parameters
//        pom {
//            project {
//                packaging 'aar'
//                // Add your description here
//                name 'a library that can auto check version on android  ' //项目描述
//                url siteUrl
//                // Set your license
//                licenses {
//                    license {
//                        name 'The Apache Software License, Version 2.0'
//                        url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
//                    }
//                }
//                developers {
//                    developer {
//                        id 'liusheng'    //填写的一些基本信息
//                        name 'AllenLiu'
//                        email '29949821@qq.com'
//                    }
//                }
//                scm {
//                    connection gitUrl
//                    developerConnection gitUrl
//                    url siteUrl
//                }
//            }
//        }
//    }
//}
//
//
//task sourcesJar(type: Jar) {
//    from android.sourceSets.main.java.srcDirs
//    classifier = 'sources'
//}
//task javadoc(type: Javadoc) {
//    options.encoding = "UTF-8"
//    source = android.sourceSets.main.java.srcDirs
//    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
//}
//task javadocJar(type: Jar, dependsOn: javadoc) {
//    classifier = 'javadoc'
//    from javadoc.destinationDir
//}
//artifacts {
//    archives javadocJar
//    archives sourcesJar
//}
//Properties properties = new Properties()
//properties.load(project.rootProject.file('local.properties').newDataInputStream())
//bintray {
//    user = properties.getProperty("bintray.user")
//    key = properties.getProperty("bintray.apiKey")
//    configurations = ['archives']
//    pkg {
//        repo = "maven"
//        name = "VersionCheckLib"    //发布到JCenter上的项目名字
//        websiteUrl = siteUrl
//        vcsUrl = gitUrl
//        licenses = ["Apache-2.0"]
//        publish = true
//    }
//}

**Comment by AlexLiuSheng** [comment]
没有的

**Comment by hy20160705** [comment]
这些东西用什么作用 可以解释一下吗

**Comment by hy20160705** [comment]
小弟不才 不是很了解

**Comment by AlexLiuSheng** [comment]
没啥用 发布项目到bintray的配置文件

**Comment by hy20160705** [comment]
搜噶  谢谢
