### ISSUE TITLE
gradle升级后3.2.0 报错

### ISSUE THREAD

**Issue by winnxiegang** [AlexLiuSheng/CheckVersionLib#204]
Android resource compilation failed
Output:  E:\company\newWinskyElectricPile\newWinskyElectricPile\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2994: error: <item> inner element must either be a resource reference or empty.
E:\company\newWinskyElectricPile\newWinskyElectricPile\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2995: error: <item> inner element must either be a resource reference or empty.
E:\company\newWinskyElectricPile\newWinskyElectricPile\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2996: error: <item> inner element must either be a resource reference or empty.
E:\company\newWinskyElectricPile\newWinskyElectricPile\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2997: error: <item> inner element must either be a resource reference or empty.
E:\company\newWinskyElectricPile\newWinskyElectricPile\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2998: error: <item> inner element must either be a resource reference or empty.

Command: C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\74ac907c744bc9daac01e2811c83b803\aapt2-3.2.0-4818971-windows\aapt2.exe compile --legacy \
        -o \
        E:\company\newWinskyElectricPile\newWinskyElectricPile\app\build\intermediates\res\merged\debug \
        E:\company\newWinskyElectricPile\newWinskyElectricPile\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0

**Comment by AlexLiuSheng** [comment]
版本多少，这个貌似不是库的问题
