### ISSUE TITLE
通知栏显示icon问题

### ISSUE THREAD

**Issue by xuekaiqi** [AlexLiuSheng/CheckVersionLib#21]
![image](https://user-images.githubusercontent.com/17778482/29255998-5d9d8546-80d9-11e7-8ca1-1ac296df73ea.png)
我的Android studio使用的是上图res文件夹  你的库是mipmap 导致通知栏图标是机器人 要怎么才能显示呢?
 要下载源码修改吗？

**Comment by AlexLiuSheng** [comment]
你在自己的项目里面 创建几个分辨率的mipmap文件夹，icon取名为ic_launcher.png  这样可以替换库的机器人图标

**Comment by xuekaiqi** [comment]
谢谢了！问题关闭吧！
