### ISSUE TITLE
下载框怎么取消呢？

### ISSUE THREAD

**Issue by DevXue** [AlexLiuSheng/CheckVersionLib#216]
通知栏既然显示下载进度以及内容了，  我此时想隐藏界面中的下载框，  取消了后提示  “”“下载失败是否重试” ， 自定义下载框，我设置了baseDialog.setCanceledOnTouchOutside(true);也不行。
   我想让他直接隐藏··  这个怎么设置呢？

**Comment by AlexLiuSheng** [comment]
用静默下载

**Comment by AlexLiuSheng** [comment]
或者设置isShowDownloadingDialog

**Comment by a120476536** [comment]
老哥 我想请问 您这个通知栏里 是如何显示进度的 。
![image](https://user-images.githubusercontent.com/7939484/65004019-7dde7f00-d92d-11e9-8be8-e657eb789e79.png)
我按照demo操作显示是更新服务正在运行
