### ISSUE TITLE
VersionService 空指针,在性能比较差的手机上偶尔会出现

### ISSUE THREAD

**Issue by yaolv7** [AlexLiuSheng/CheckVersionLib#218]
先执行了VersionService#onDestroy()的builder = null; (DownloadBuilder = null)
然后才执行异步的VersionService#requestVersion()的builder.setVersionBundle(versionBundle);
此时就会报空指针,华为的手机出现特别多,基本上接近50%了

建议加个判空处理,或者取消所有handler的任务

**Comment by AlexLiuSheng** [comment]
谢谢，刚更新了2.1.7，如果有问题再打开
