### ISSUE TITLE
混淆出错

### ISSUE THREAD

**Issue by cnkker** [AlexLiuSheng/CheckVersionLib#219]
Expecting java type before ';' 

-keepclassmembers class * {    @org.greenrobot.eventbus.Subscribe ;}
这行报错

**Comment by awsyawsa** [comment]
这个是怎么解决的呀  我也遇到了这个问题

**Comment by Piscen** [comment]
我也遇到这个问题，

**Comment by SephirothLT** [comment]
-keepattributes Annotation
 -keepclassmembers class ** {
     @org.greenrobot.eventbus.Subscribe <methods>;
 }
   -keep enum org.greenrobot.eventbus.ThreadMode { *; }
   -keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
       <init>(java.lang.Throwable);
   }
   -keep class com.allenliu.versionchecklib.**{*;}
@Alex
 建议更新混淆配置
