### ISSUE TITLE
下载对话框

### ISSUE THREAD

**Issue by xuekaiqi** [AlexLiuSheng/CheckVersionLib#22]
![image](https://user-images.githubusercontent.com/17778482/29259933-ef39d1f2-80f8-11e7-9385-4990db5db8b9.png)
下载对话框 宽度怎么改变不了？ 无论怎么布局  宽度始终是一致的！ 怎么能改变宽高，居中显示在屏幕中间

**Comment by AlexLiuSheng** [comment]
改变宽高不能用系统的AlertDialog.setView的方式，它宽是AlertDialog固定的.你得自己定义一个dialog来设置。

**Comment by xuekaiqi** [comment]
谢谢了！可以关闭了！

**Comment by xuekaiqi** [comment]
自定义正在下载对话框 运行7.0的华为手机下载的时候出现了ANR  自定义下载对话框在哪dismiss

**Comment by AlexLiuSheng** [comment]
ANR 应该是你每次都初始化了对话框。注意showLoadingDialog下载的时候会一直回调的。所以不要在里面每次都创建dialog。   自定义对话框dismiss库还没实现。。。。等我改一下

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.1'
自定义loading dialog 使用父类的loadingDialog 它继承自Dialog。下载完成库会自动dimiss
