### ISSUE TITLE
https的下载路径，无法监听下载进度

### ISSUE THREAD

**Issue by SmilingBoy** [AlexLiuSheng/CheckVersionLib#220]

**Comment by SmilingBoy** [comment]
刚刚又仔细看了一下，不是https的原因，是后台设置了gzip，获取到的contentLength是-1，所以，进度条会显示负数，解决方式：在Header中加入：Request.Builder().addHeader("Accept-Encoding", "identity")

**Comment by AlexLiuSheng** [comment]
感谢，已经加入了header
