### ISSUE TITLE
强制更新优化意见

### ISSUE THREAD

**Issue by dazhi3219** [AlexLiuSheng/CheckVersionLib#225]
如果要求强制升级，点击“确定”之后弹窗最好不要消失，如果用户存储权限禁止了，就强制不了了，或者下载了没有安装，也能继续使用旧的版本。最好是点击“确定‘有个设置选项是否有弹窗消失的选项，或者在存储权限点击禁止的时候有个回调，做一些处理操作

**Comment by AlexLiuSheng** [comment]
感谢issue，对于强制更新需要说明
1.静默下载的强制更新无效。
2.之前由于禁止读写权限强制失败，现已修复
强更需要你自己在回调中关闭你所有的界面，程序会下载完成立即回调forceUpdateListener然后再到安装界面，所以在回调中你应该就该关闭你的app的所有界面，就算用户取消了安装， 那么app就已经退出了这是我的思路
