### ISSUE TITLE
关于强制更新

### ISSUE THREAD

**Issue by seul8660** [AlexLiuSheng/CheckVersionLib#226]
作者的做法是在下载完成时判断是否强制更新，强制更新则关闭所有activity。但是实际测试中，用户可以只要取消安装就可以绕过。建议做法是当下载完成时（即forceUpdateListener回调）再次显示出更新dialog。这样用户取消安装再进入也有更新dialog，而不至于绕过更新。

**Comment by AlexLiuSheng** [comment]
感谢issue，对于强制更新需要说明
1.静默下载的强制更新无效。
2.之前由于禁止读写权限强制失败，现已修复
强更需要你自己在回调中关闭你所有的界面，程序会下载完成立即回调forceUpdateListener然后再到安装界面，所以在回调中你应该就该关闭你的app的所有界面，就算用户取消了安装， 那么app就该退出了这是我的思路
