### ISSUE TITLE
androidx.constraintlayout:constraintlayout:2.0.0-alpha3 issue

### ISSUE THREAD

**Issue by dennislan** [AlexLiuSheng/CheckVersionLib#227]
Compile error
Android resource compilation failed
app/build/intermediates/incremental/mergeAresDebugResources/merged.dir/values/values.xml:4957: error: duplicate value for resource 'attr/pivotX' with config ''.
app/build/intermediates/incremental/mergeAresDebugResources/merged.dir/values/values.xml:4957: error: resource previously defined here.
app/build/intermediates/incremental/mergeAresDebugResources/merged.dir/values/values.xml:4957: error: duplicate value for resource 'attr/pivotY' with config ''.
app/build/intermediates/incremental/mergeAresDebugResources/merged.dir/values/values.xml:4957: error: resource previously defined here.

alpha2 compile ok.

thks!

**Comment by AlexLiuSheng** [comment]
in the version of 2.1.9  has removed the dependency of constraintlayout:2.0.0-alpha3

**Comment by dennislan** [comment]
It's Working, Good Job!
Thks!
