### ISSUE TITLE
报错奔溃

### ISSUE THREAD

**Issue by liuyu1212120** [AlexLiuSheng/CheckVersionLib#229]
Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3dadbcd u0 com.ronchain/com.allenliu.versionchecklib.v2.ui.VersionService}

**Comment by AlexLiuSheng** [comment]
之前在service收到eventbus粘性事件才设置前台，所以可能导致问题 ，现已经修复
