### ISSUE TITLE
有个空指针，需要判断下

### ISSUE THREAD

**Issue by Key-CN** [AlexLiuSheng/CheckVersionLib#24]
@Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        Log.e("onStartCommand", "intent: " + intent);
        if (intent != null) {
            versionParams = intent.getParcelableExtra(VERSION_PARAMS_KEY);
            requestVersionUrlSync();
        }
        return super.onStartCommand(intent, flags, startId);
    }

你可以发现不加判断，崩溃的时候，intent打印出来是null

**Comment by AlexLiuSheng** [comment]
好的 我改下
