### ISSUE TITLE
dialogDismiss 一直回调不到

### ISSUE THREAD

**Issue by wudaobin** [AlexLiuSheng/CheckVersionLib#25]
VersionDialogActivity 中缺少调起吧
 @Override
    public void onDismiss(DialogInterface dialogInterface) {
    }
这里什么都没有，cancelListener都没用到啊。

**Comment by AlexLiuSheng** [comment]
`versionDialog.setOnDismissListener(this);`
你设置这个没有

**Comment by wudaobin** [comment]
设置了

**Comment by wudaobin** [comment]
你的示例代码，使用自定义界面时，在出现更新界面，但是在点击取消，会back键，出现不能操作，要再次点击back，因为CustomVersionDialogActivity并没有被finish

**Comment by AlexLiuSheng** [comment]
就是因为没有回调dialogdismiss的原因，我解决下

**Comment by wudaobin** [comment]
我在你库的VersionDialogActivity的
@Override
    public void onDismiss(DialogInterface dialogInterface)
    {
        if (cancelListener!=null)
        {
            cancelListener.dialogDismiss(dialogInterface);
        }
    }
做了修改，它才调起

**Comment by AlexLiuSheng** [comment]
嗯嗯 之前重构代码的时候 这个回调忘了

**Comment by wudaobin** [comment]
有个地方我想问下哈，就是强制更新这个设置，在勾选了强制更新后，按示例代码中的写法，点击更新，app不就被关闭了？但是下载任务才刚开始，app崩溃啊。。。。

**Comment by AlexLiuSheng** [comment]
对啊 我在想这个问题 还是的设置取消和消失不是一个概念

**Comment by AlexLiuSheng** [comment]
要区分一下这个

**Comment by wudaobin** [comment]
要关联下载完成的状态

**Comment by AlexLiuSheng** [comment]
解决了

**Comment by AlexLiuSheng** [comment]
你看看，好了的话close下issues

**Comment by wudaobin** [comment]
可以！就是在示例代码的onDownloadSuccess回调中觉得加上是否强制更新判断处理。或者在其他地方处理？

**Comment by AlexLiuSheng** [comment]
只能在onDialogDissmiss里面处理强制更新

**Comment by wudaobin** [comment]
是下载成功，并没有把app关闭了，应该在下载成功时关闭

**Comment by wudaobin** [comment]
@Override
    public void onDownloadSuccess(File file)
    {
        Logger.e("文件下载成功回调");
        if (isAutoInstall)
        {
            MainActivity.mainActivity.finish();
        }
    }

**Comment by AlexLiuSheng** [comment]
额。。什么意思啊？我没懂你的意思

**Comment by wudaobin** [comment]
当用户选择下载更新时，在CustomVersionDialogActivity的onDownloadSuccess里，我们应该加上关闭app的代码。要不用户下载了，而不安装，应用还是在开着的，强制更新就。。。。不强制了

**Comment by AlexLiuSheng** [comment]
我觉得强制更新判断应该在versionDialog点击确定或者取消的时候，如果系统需要强制更新，那么用户点击取消操作，就应该直接关闭app。只有用户点击确定之后，才会执行后面的一系列下载和安装操作。

**Comment by AlexLiuSheng** [comment]
😅我懂你的意思了

**Comment by AlexLiuSheng** [comment]
那我在下载成功的时候，在回调一次dialogDissmiss方法

**Comment by AlexLiuSheng** [comment]
😄多谢指点哈，有些时候一个人考虑没有这么全面
