### ISSUE TITLE
大佬 怎么监听点击物理返回键不让提示升级的弹窗隐藏

### ISSUE THREAD

**Issue by nanian** [AlexLiuSheng/CheckVersionLib#256]

**Comment by nanian** [comment]
大佬 怎么监听点击物理返回键不让提示升级的弹窗隐藏

**Comment by a120476536** [comment]
这个屏蔽就好了 baseDialog.setOnKeyListener(new DialogInterface.OnKeyListener() {
                    @Override
                    public boolean onKey(DialogInterface dialog, int keyCode, KeyEvent event) {
                        if (keyCode == KeyEvent.KEYCODE_BACK) {
                            return true;
                        }
                        return false;
                    }
                });

**Comment by AlexLiuSheng** [comment]
fixed in 2.2.2
