### ISSUE TITLE
关于builder.setNewestVersionCode()调用时机问题

### ISSUE THREAD

**Issue by Wilshion** [AlexLiuSheng/CheckVersionLib#258]
首先还是得感谢作者，给大家在更新apk提供了这么方便的库。
今天第一次使用，sample 中 唯一关于 setNewestVersionCode 方法调用还被注释掉了。所以有点疑惑，最新的VersionCode 是需要从服务器获取到，所以需要在RequestVersionListener 的回调中获取到并设置，此时该如何设置呢？

**Comment by AlexLiuSheng** [comment]
如果使用请求版本+下载的话，只能设一个全局变量或者静态变量

**Comment by Wilshion** [comment]
好的，感谢回复，不过定义全局或者静态变量的话应该不行的，因为这有个异步过程的，除非我先请求一次版本信息，在请求到版本信息后再去调用老哥你这边的更新库去下载更新（包括设置最新版本号的方式）。

**Comment by AlexLiuSheng** [comment]
应该是可以的，这个版本号只会在下载之前，请求服务器版本之后使用
