### ISSUE TITLE
安装包比较大时crash问题

### ISSUE THREAD

**Issue by taozhixiang** [AlexLiuSheng/CheckVersionLib#263]
我的安装包差不多19M，然后下载一般的时候软件就崩溃了。如果是比较小的安装包。就没啥问题。有人遇到过吗？能否提供一下技术支持。

**Comment by taozhixiang** [comment]
不是包大的问题。网络较慢时会crash 。

**Comment by AlexLiuSheng** [comment]
没日志也看不出问题来

**Comment by taozhixiang** [comment]
@AlexLiuSheng 方便加一下我的qq吗？609395997.
