### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by ProfessionalMe** [AlexLiuSheng/CheckVersionLib#267]
如果不是强制更新。当下载中的时候点击返回键，CancelListener就执行了，点击下载失败对话框的取消按钮CancelListener也会执行，提示更新Dialog中点击取消，CancelListener也会执行，但是这三个动作我可能要执行不一样的操作， 可不可以把提示更新  下载失败  的点击分别开放出来？

**Comment by AlexLiuSheng** [comment]
fixed in 2.2.2
