### ISSUE TITLE
如何在通知栏显示下载进度

### ISSUE THREAD

**Issue by a120476536** [AlexLiuSheng/CheckVersionLib#271]
如题
builder.setNotificationBuilder(
                NotificationBuilder.create()
                        .setRingtone(true)
                        .setIcon(R.mipmap.ic_launcher)
                        .setTicker("title")
                        .setContentTitle("title")
                        .setContentText(getString(R.string.custom_content_text))
        );

 .setContentText(getString(R.string.custom_content_text)) 如何把下载进度跟这个关联起来？请教大佬
试了下demo里边也是提示正在更新中

**Comment by AlexLiuSheng** [comment]
这个可能需要改下，2.0之后这里确实忘记了

**Comment by AlexLiuSheng** [comment]
看了下  之前是可以显示进度的 ，具体请看R.string.custom_content_text
