### ISSUE TITLE
静默下载+强制更新无法执行到强制更新的回调

### ISSUE THREAD

**Issue by Samdogcom** [AlexLiuSheng/CheckVersionLib#274]
设置了setSilentDownload(true)
再加上强制更新,无法执行到回调
问题在于AppUtils.installApk里最后一行执行了
AllenVersionChecker.getInstance().cancelAllMission(context);
里面执行了VersionService.builder=null;
以至于在AllenBaseActivity里的checkForceUpdate条件永远为假
因为getVersionBuilder()已经为Null了

**Comment by AlexLiuSheng** [comment]
静默下载不允许强制更新，这本身就是一个伪命题

**Comment by Samdogcom** [comment]
本来我也是这样想,感觉有点矛盾,看到你Demo里有得选就选来试了下,结果就是提示框是强制更新的样式没有取消键,但是最后没有执行到回调,再看你源码,在dealVersionDialogCommit里都一直有静默的判断还有checkForceUpdate去触发回调,所以以为你本意是可以这样组合的,刚好我的项目还真想这样用,因为下载的时候不想打扰用户,等下载完后用户就必须强制更新才能继续使用了
所以我把AppUtils.installApk的最后一行注释掉就可以正常了,不知道有没有什么影响
你所说的静默下载不允许强制更新应该是那种先弹出更新提示框,点确定后开始静默下载,App可以继续使用,下载完后直接安装吧,我现在需求的反而是现在这种先下载再弹框的,感觉两种模式都有一定的需求
