### ISSUE TITLE
自定义Dialog，点不动下载按钮

### ISSUE THREAD

**Issue by AwaiTYu** [AlexLiuSheng/CheckVersionLib#275]
自定义dialog之后，日志也打印的立即下载的按钮对象是有的，但是就是不能点击，用你默认的就能下载，用我自定义的dialog，就是不能点击，也不知道哪一步出错了，我太难了
![image](https://user-images.githubusercontent.com/28527497/65240090-0cf8bc00-db13-11e9-8ee0-edcb9c7f0bef.png)

**Comment by AlexLiuSheng** [comment]
id用没用对

**Comment by AwaiTYu** [comment]
对着呢，不然那个view not null那个log就不会打印的，findViewById就直接会找不到的
![image](https://user-images.githubusercontent.com/28527497/65240443-e12a0600-db13-11e9-8942-4066003a38fd.png)
![image](https://user-images.githubusercontent.com/28527497/65240501-00c12e80-db14-11e9-84d6-2907d1fe7d9b.png)

**Comment by AlexLiuSheng** [comment]
@+id 改成@id

**Comment by AlexLiuSheng** [comment]
而且不用设点击事件，库自动会设置，具体可参考demo，自定义dialog

**Comment by AwaiTYu** [comment]
改了@+id也不行，还有就是那个点击事件，我没有设置，我是直接把你的库，下载下来当library以project的方式让主项目依赖的，我上面的图片就是你项目中的源码showCustomDialog（）这个方法，在你库UIActivity里面

**Comment by AlexLiuSheng** [comment]
运行demo试试，dialog实例化也要用库传回来的context，多看看demo

**Comment by AlexLiuSheng** [comment]
demo里有自定义dialog

**Comment by AwaiTYu** [comment]
是我自己的问题，刚解决，作者给了灵感，是创建dialog出的问题，我按着作者Demo里面的BaseDialog写了一个没问题了，多谢作者！可以的话，希望作者适配一下Q，升级到androidx吧
