### ISSUE TITLE
解析包时出现问题 小米华为都不行

### ISSUE THREAD

**Issue by Wutinie** [AlexLiuSheng/CheckVersionLib#276]
小米华为手机测试，解析包出现问题，不能安装
shmilx 的方法试过也不行

**Comment by Wutinie** [comment]
经测试builder.setDownloadAPKPath（getExternalFilesDir（“”））导致的
不添加这行安装成功

**Comment by AlexLiuSheng** [comment]
路径要以“/”结尾
