### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by hzq19920817** [AlexLiuSheng/CheckVersionLib#278]
下载途中点击物理返回键取消下载，然后又点击下载，出现内存泄漏
![图片](https://user-images.githubusercontent.com/14231403/65419498-5a399e00-de31-11e9-9f9b-d9d3570184d5.png)

**Comment by AlexLiuSheng** [comment]
试试2.2.1，还有看看你回调的里有没有涉及引用activity之类的引用，如果有在activity销毁时cancelMission

**Comment by hzq19920817** [comment]
其实是你UIActivity下面的Dialog持有了这个引用，我下源码下来改了就行了，如果你用系统的AlertDialog初始化Dialog,只要定义了按钮事件就会出现这个问题
