### ISSUE TITLE
你好,会冲突吗?

### ISSUE THREAD

**Issue by zuowutan** [AlexLiuSheng/CheckVersionLib#28]
我这边项目使用到的OKGO版本是3.0.4  朋友你使用的是OKGO版本是2.1.4  请问两个会冲突吗?

**Comment by AlexLiuSheng** [comment]
不会的。默认会merge的

**Comment by zuowutan** [comment]
那如果直接使用OKGO3.0.4版本,这样对版主的功能有影响吗

**Comment by AlexLiuSheng** [comment]
不会有影响

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.6.0'
移除了okgo使用okhttp替代
