### ISSUE TITLE
在Android10中下载一直提示失败

### ISSUE THREAD

**Issue by wqjuser** [AlexLiuSheng/CheckVersionLib#283]

**Comment by meilyzh** [comment]
请问android 10 中下载失败解决了吗

**Comment by HarlanSong** [comment]
期待问题修复

**Comment by withyoulxz** [comment]
Demo运行在Android10手机上可以正常下载更新，但是集成到项目中还是一直下载失败

**Comment by wuhongsheng** [comment]
我也是，日志打印下载，没有找到原因

**Comment by feng88724** [comment]
这个问题很严重啊，需要尽快修复才行

**Comment by ddxxll2008** [comment]
demo可以运行，但是集成在项目中显示下载失败

**Comment by ddxxll2008** [comment]
> Demo运行在Android10手机上可以正常下载更新，但是集成到项目中还是一直下载失败

设置下载路径为：
builder.setDownloadAPKPath(this.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS).getPath());
