### ISSUE TITLE
downloadOnly如何去掉dialog直接下载？v2.2.1仍有此问题

### ISSUE THREAD

**Issue by JiangShuLiang** [AlexLiuSheng/CheckVersionLib#286]
AllenVersionChecker
                                .getInstance()
                                .downloadOnly(
                                        UIData.create().setDownloadUrl(“http://xxxxxxxx.apk”)
                                ).executeMission(context);

**Comment by AlexLiuSheng** [comment]
builder.setDirectDownload(true);
