### ISSUE TITLE
VersionService.java中发送“CLOSE_DOWNLOADING_ACTIVITY”事件太快导致的bug

### ISSUE THREAD

**Issue by xiangyouxinsheng1314** [AlexLiuSheng/CheckVersionLib#287]
CLOSE_DOWNLOADING_ACTIVITY事件在下载失败的情况下，有时会导致在DownloadingActivity启动之前发送事件，这样就接收不到事件了，DownloadingActivity就销毁不了，需要把CLOSE_DOWNLOADING_ACTIVITY改成粘性事件发送

**Comment by AlexLiuSheng** [comment]
fixed in 2.2.2
