### ISSUE TITLE
下载时，因为连接无法下载，不报下载失败

### ISSUE THREAD

**Issue by lhhseraph** [AlexLiuSheng/CheckVersionLib#290]
![image](https://user-images.githubusercontent.com/10457402/69321147-8a5cbc00-0c7d-11ea-82fa-150511db2512.png)
下载时，因为连接无法下载，报404，但程序扔继续保存数据为apk 并且去安装，提示解析失败，不报下载失败错误。

**Comment by AlexLiuSheng** [comment]
已解决
