### ISSUE TITLE
更新服务正在运行 这个notification 怎么取消

### ISSUE THREAD

**Issue by chinaliuweijie** [AlexLiuSheng/CheckVersionLib#295]
setShowNotification 这个没有用啊

**Comment by chinaliuweijie** [comment]
弹出版本更新对话框后，下拉出来会有一个通知提示更新服务正在运行，这个通知怎么取消不让显示

**Comment by higsx** [comment]
DownloadBuilder downloadBuilder = AllenVersionChecker.getInstance().downloadOnly(ui);
        //关闭 通知栏的 通知 ,有些 手机直接回报错.
        downloadBuilder.setShowNotification(false);

我可以用哈

**Comment by chinaliuweijie** [comment]
setShowNotification  这个方法没用啊

**Comment by chinaliuweijie** [comment]
应该是后台起了一个服务，android 规定服务必须有一个notification，必须有这个通知，这个怎么取消啊

**Comment by AlexLiuSheng** [comment]
**2.2.0**  setRunOnForegroundService  最好以前台服务运行 防止后台更新进程被杀死

**Comment by AlexLiuSheng** [comment]
2.2.2
