### ISSUE TITLE
默认下载文件路径无法创建

### ISSUE THREAD

**Issue by grliao** [AlexLiuSheng/CheckVersionLib#31]
在华为荣耀6,Android 6.0的版本上,根据默认路径(
/storage/emulated/0/AllenVersionPath/)创建下载文件抛异常的.具体在FileCallBack 的60行.默认为app当前私有目录是可以的.

**Comment by AlexLiuSheng** [comment]
是静默下载？

**Comment by AlexLiuSheng** [comment]
我知道了 这是个bug马上修复

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.6.3' 你看解决了关闭下issue

**Comment by grliao** [comment]
代码逻辑还是有点问题的文件,存在先删除,后续再创建.

**Comment by grliao** [comment]
if (file.exists()) {
                file.delete();
            } else {
                file.createNewFile();
            }

**Comment by AlexLiuSheng** [comment]
现在还是不行吗？之前是少了个动态读写权限申请 这个逻辑是保证每次下载都是重新下载

**Comment by grliao** [comment]
是的,错误是:
java.io.FileNotFoundException: /storage/emulated/0/AllenVersionPath/com.allenliu.sample.apk: open failed: EACCES (Permission denied)

**Comment by AlexLiuSheng** [comment]
按理说不会存在这个问题了，库已经做了权限申请，如果不行你自己在项目中先申请权限

**Comment by grliao** [comment]
弹出申请权限确认框,导致Activity已经关闭,你把你的demo先删除再安装看看就清楚了.

**Comment by AlexLiuSheng** [comment]
1.6.4已经解决了
