### ISSUE TITLE
适配AndroidQ问题

### ISSUE THREAD

**Issue by zhengjunke** [AlexLiuSheng/CheckVersionLib#313]
2.3.4以前的版本，在Android Q的设备无法升级，升到2.3.4之后，有些低版本的系统无法升级，比如小米的一些Android6.0，华为荣耀的Android8.0，不过我这边基于你的库做了一些修改，能否交流一下

**Comment by shengdoushi** [comment]
提下 pull request 吧

**Comment by chenqunqq123** [comment]
> 2.3.4以前的版本，在Android Q的设备无法升级，升到2.3.4之后，有些低版本的系统无法升级，比如小米的一些Android6.0，华为荣耀的Android8.0，不过我这边基于你的库做了一些修改，能否交流一下

我的也是，之前把项目从git上面拉下来直接打包了 ，现在线上很多手机更新不了，坑太深了

**Comment by zhufengi** [comment]
坑有点深.... 我的也是

**Comment by AlexLiuSheng** [comment]
这个应该是路径问题，之前的版本可以考虑自己设置下载文件路径。由于我这边无法复现，在2.4.1版本中单独加了针对AndroidQ以上的路径判断，可以观察下
