### ISSUE TITLE
okhttp报错，路过的大佬帮忙看一下

### ISSUE THREAD

**Issue by FynnJason** [AlexLiuSheng/CheckVersionLib#316]
# OkHttp Dispatcher(53682)

java.lang.NoSuchMethodError

No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/com.xxx.xxx-dXwWFBygTzC6KEehXwShzA==/base.apk!classes14.dex)

**Comment by LCJIAN** [comment]
implementation('com.github.AlexLiuSheng:CheckVersionLib:2.2.4') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
