### ISSUE TITLE
android 6 下下载后无法安装

### ISSUE THREAD

**Issue by grliao** [AlexLiuSheng/CheckVersionLib#32]
下载apk包安装时出现"解析包时出现问题"的错误.

**Comment by AlexLiuSheng** [comment]
这个是测试的下载链接 失效了 你自己另外设置一个呢

**Comment by grliao** [comment]
你好,我是使用自己实现的请求url的.我看下载完毕了,执行安装的时候失败了.由于是私有目录,并且华为荣耀6无法root,所以无法直接找到apk入门直接手动安装.

**Comment by AlexLiuSheng** [comment]
已经解决了 试试最新版

**Comment by grliao** [comment]
我这边是使用你的Sample 和 ForceUpdateDemo 测试的.只是requesturl 是我自己的,解析也是我直接实现的.

**Comment by grliao** [comment]
我这边是使用你的Sample 和 ForceUpdateDemo 测试的.只是requesturl 是我直接的,解析也是我直接实现的.

**Comment by grliao** [comment]
好的

**Comment by AlexLiuSheng** [comment]
传入下载地址对不对

**Comment by AlexLiuSheng** [comment]
你重新clone一下

**Comment by AlexLiuSheng** [comment]
之前我传的那个下载链接失效了

**Comment by grliao** [comment]
好的,我测试一下

**Comment by grliao** [comment]
这个我测试了,发现设置默认下载路径为this.getApplicationContext().getFilesDir() + "/" 会出现上面的错误

**Comment by AlexLiuSheng** [comment]
也就是自定义的下载路径会出问题么

**Comment by AlexLiuSheng** [comment]
解决了1.6.5 之前FileProvider只设置了对外部文件支持还有root path没有设置，现在修复好了 感谢提出问题🙏
