### ISSUE TITLE
用的之前的版本，移动网络情况下无法下载aPk?

### ISSUE THREAD

**Issue by helloworkcupid** [AlexLiuSheng/CheckVersionLib#322]
com.allenliu.versionchecklib:library:2.1.9,项目集成依赖。其他都还算正常，但是在使用流量的情况下，无法开始下载apk,请问可以解决吗？

**Comment by zhufengi** [comment]
我晕，我也是之前版本遇到了，看来真的有问题

**Comment by AlexLiuSheng** [comment]
无法复现 建议使用新版

**Comment by helloworkcupid** [comment]
关于网络情况的影响，如果使用内网呢？就是网络情况被设置为内网，外网都可以，但是还是有限制，这时候弹不出升级框，请问有好的办法吗？
