### ISSUE TITLE
更新弹窗有问题，前后换换有时不走自定义弹窗

### ISSUE THREAD

**Issue by chenqunqq123** [AlexLiuSheng/CheckVersionLib#324]
更新时，前后切换 UIActivity类中 if (getVersionBuilder() != null && getVersionBuilder().getCustomVersionDialogListener() != null) {
            showCustomDialog();
        } else {
            showDefaultDialog();
        }
getVersionBuilder().getCustomVersionDialogListener() 第一次不为空   第二次为空

**Comment by TWBfly** [comment]
Same problem。打开APP首页MainActivity升级，自定义弹窗正常，然后切换至后台，杀死应用，重新打开，可复现此bug。
![image](https://user-images.githubusercontent.com/21956119/100494681-e1de1380-317e-11eb-8af1-e7903409ae8e.png)

**Comment by TWBfly** [comment]
已fix，得在首页做销毁处理
![image](https://user-images.githubusercontent.com/21956119/100494994-07b8e780-3182-11eb-9bf3-aff8b0ddeb9b.png)
