### ISSUE TITLE
权限相关的建议

### ISSUE THREAD

**Issue by JingweiWang** [AlexLiuSheng/CheckVersionLib#329]
1. 建议可以自定义是否使用库内默认的权限检查。
2. 建议新增权限监听回调，让用户进行处理，并且不自动关闭对话框。

谢谢，以上。

**Comment by wangxue** [comment]
这个库的权限处理导致用户可以绕过强制升级，两年前的pull request还挂在那呢，还是自己fork修改吧

**Comment by JingweiWang** [comment]
> 这个库的权限处理导致用户可以绕过强制升级，两年前的pull request还挂在那呢，还是自己fork修改吧

您说的很多 已经该用其他方案。

这个库确实可惜了。

**Comment by AlexLiuSheng** [comment]
可以看下2.4.1应该解决了
