### ISSUE TITLE
设置成静默下载，会出现下载失败的情况。

### ISSUE THREAD

**Issue by HeWenhui** [AlexLiuSheng/CheckVersionLib#33]
静默下载，看代码直接调用下载模块，那如果在6.0之后的手机上，在下载之前没有请求SD卡读写权限。导致如果没有权限，会直接回调OnDownLoadFail。显示进度条的下载是做了权限请求的，不会有此问题。所以如果需求是静默下载的话，最好在调用之前，做一下读写权限的检查。

**Comment by AlexLiuSheng** [comment]
谢谢指出问题，1.6.6已经解决了

**Comment by stefanieghq** [comment]
Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class

**Comment by AlexLiuSheng** [comment]
V1版停止维护
