### ISSUE TITLE
Android 11，新版本安装失败

### ISSUE THREAD

**Issue by ryanxia2016** [AlexLiuSheng/CheckVersionLib#332]
android 10 及之前版本还OK

但android11 上，可以调起安装界面，之后就提示包体解析失败

看日志是:
OPInstallStaging: Error staging apk from content URI
    java.io.FileNotFoundException: No content provider: content://.....

**Comment by AlexLiuSheng** [comment]
下载路径需要用app内部的 不要用外置存储卡的
