### ISSUE TITLE
VersionService类中大量报NullPointerException

### ISSUE THREAD

**Issue by chen3441251** [AlexLiuSheng/CheckVersionLib#336]
Attempt to invoke virtual method 'boolean com.allenliu.versionchecklib.v2.builder.DownloadBuilder.isRunOnForegroundService()' on a null object reference

com.allenliu.versionchecklib.v2.ui.VersionService.onDestroy(VersionService.java:103)

**Comment by AlexLiuSheng** [comment]
2.4.1可以看下，由于历史代码原因

**Comment by chen3441251** [comment]
大佬好久没见更新版本了，以为你不维护了呢，哈哈。甚是想念
