### ISSUE TITLE
targetsdk 改为19  在安卓7上使用就会崩溃

### ISSUE THREAD

**Issue by BigBigDeBoy** [AlexLiuSheng/CheckVersionLib#34]

**Comment by AlexLiuSheng** [comment]
报什么错

**Comment by BigBigDeBoy** [comment]
Android7.1.1，在FileCallback类里，  File file = convert.convertSuccess(response);
进入异常java.io.FileNotFoundException: /data/AllenVersionPath/VersionCheckLib.apk (No such file or directory)。文件夹没有创建，导致报错

**Comment by AlexLiuSheng** [comment]
你是自己指定的下载路径么
