### ISSUE TITLE
关于写存储卡权限的获取

### ISSUE THREAD

**Issue by HIK-wanglu** [AlexLiuSheng/CheckVersionLib#343]
现在是不管待更新的安装包下载在哪里，都需要WRITE_EXTERNAL_STORAGE这个权限，这个是不是不太合理？

**Comment by wjwang0914** [comment]
我看了源码文件保存在应用的外置sdk里面 应该是不用申请权限

**Comment by SunOfBeach2** [comment]
2.4.2 去除读写权限适配到android13
