### ISSUE TITLE
如何取消正在进行的进程？

### ISSUE THREAD

**Issue by ycads** [AlexLiuSheng/CheckVersionLib#35]
有遇到这样的情况，进度一直是负数，我需要监听是负数的时候，自动取消下载进程，这个如何实现？

**Comment by AlexLiuSheng** [comment]
非静默下载的情况下，进度监听是在VersionDialogActivity里，如果你想取消直接finish这个activity就行了

**Comment by ycads** [comment]
OK，为什么会出现负数，但是最终可以下载成功，是不是计算进度的问题？
