### ISSUE TITLE
下载进度Dialog出现时，点击home键或者锁屏键，Dialog会消失

### ISSUE THREAD

**Issue by ZevShiShi** [AlexLiuSheng/CheckVersionLib#350]
版本是com.github.AlexLiuSheng:CheckVersionLib:2.4.1_androidx

**Comment by ZevShiShi** [comment]
找到问题了，是作者在DownloadingActivity的onPause方法中调用了destroyWithOutDismiss，把dialog给dismiss了= =
```kotlin
    override fun onPause() {
        super.onPause()
        destroyWithOutDismiss()
        isDestroy = true
    }
```

**Comment by chaozi0118** [comment]
> 找到问题了，是作者在DownloadingActivity的onPause方法中调用了destroyWithOutDismiss，把dialog给dismiss了
> 
> ```kotlin
>     override fun onPause() {
>         super.onPause()
>         destroyWithOutDismiss()
>         isDestroy = true
>     }
> 
>     private fun destroyWithOutDismiss() {
>         downloadingDialog?.let {
>             if (it.isShowing) {
>                 it.dismiss()
>             }
>         }
>     }
> ```
> 
> 建议作者更新修复一下代码
怎么解决的

**Comment by SunOfBeach2** [comment]
2.4.2
