### ISSUE TITLE
用户下载一遍了，安装的时候点取消，下次打开又要重新下载。v1.6.6

### ISSUE THREAD

**Issue by changjiashuai** [AlexLiuSheng/CheckVersionLib#37]

**Comment by AlexLiuSheng** [comment]
是直接运行的demo？ demo里下载的apk和demo的包名不是一样的 所以会存在问题 你直接集成到项目呢

**Comment by changjiashuai** [comment]
自己项目里

**Comment by 897902334** [comment]
这个问题解决了么 ？  我也是发现     就算我下载完了， 我没有安装，  然后我再次点击发起求情   还是执行的下载流程，   并没有直接安装的功能！   希望作者看看这个问题。   我用demo测试的。

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.7.7'
