### ISSUE TITLE
设置成静默下载报错

### ISSUE THREAD

**Issue by awsyawsa** [AlexLiuSheng/CheckVersionLib#39]
在DemoService的onResponses方法中调用showVersionDialog出错，出错信息：Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.
非静默下载中添加了 intent.addFlags(268435456)，而静默下载并没有，是这个原因吗？

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.6.7'
