### ISSUE TITLE
建议减少库的依赖

### ISSUE THREAD

**Issue by ittianyu** [AlexLiuSheng/CheckVersionLib#4]
把lib和demo分开为独立的模块，可以让库少用一个 com.alibaba:fastjson:1.2.17
另外建议能用通用的库就用通用的库，把 okhttputils 换成 okhttp3。
可以减少引入本库后增加的体积。

**Comment by AlexLiuSheng** [comment]
不好意思前段时间一直忙 现在全部重做了 可自定义界面
