### ISSUE TITLE
requestUrl作为请求版本接口url的作用是什么，为空时闪退。。。

### ISSUE THREAD

**Issue by Aarondue** [AlexLiuSheng/CheckVersionLib#40]
VersionParams.Builder builder = new VersionParams.Builder()
                .setRequestUrl("http://www.baidu.com")
                .setCustomDownloadActivityClass(CustomDialogActivity.class)
                .setService(MyService.class);

Retrofit mRetrofit = new Retrofit.Builder()
                    .baseUrl(URL)
                    .addConverterFactory(GsonConverterFactory.create(gson))
                    .client(okHttpClient)
                    .build();
问题1：“setRequestUrl("http://www.baidu.com")”的作用相当于Retrofit 中的“baseUrl(URL)”么？
好像除了为空外随便输什么网址都可以啊。
问题2：既然上面已经设置了一个url，但showVersionDialog("downloadUrl","test","test",bundle)中的downloadUrl仍然要求是apk的完整url地址，这样做是为了什么？

**Comment by AlexLiuSheng** [comment]
setRequestUrl是设置你服务端版本请求接口的地址，库会帮你请求接口然后你需要关注的就是自己在onResponse里面解析数据判断是否需要升级，升级就调用showVersionDialog("downloadUrl","test","test",bundle)。然后库会帮你下载和安装apj
所以requesturl是必须的

**Comment by Aarondue** [comment]
我现在有一个完整apk的url地址String URL= “http://mysteelapi.steelphone.com/v4/download/4.6.2/app-MySteel-release.apk”，现在将其拆分成两部分，其中String baseUrl = “http://mysteelapi.steelphone.com/v4/”是我们的服务器地址，
String downloadUrl = “download/4.6.2/app-MySteel-release.apk”是请求接口。
经过测试，只要showVersionDialog("downloadUrl","test","test",bundle)中传入完整URL，setRequestUrl传入任何非空值都能正确运行且版本下载更新。还是搞不懂setRequestUrl的作用。这和Retrofit 的使用不太一样的，Retrofit 只要前面传入了baseUrl，后面只需要请求接口即可，不需要完整Url的。


我是以下传值方式，即使setRequestUrl仍然传入“http://www.baidu.com”，仍然没问题。

VersionParams.Builder builder = new VersionParams.Builder()
.setRequestUrl(baseUrl )
.setCustomDownloadActivityClass(CustomDialogActivity.class)
.setService(MyService.class);

showVersionDialog(URL,"test","test",bundle)

**Comment by Aarondue** [comment]
懂了，我们没有一个单独用于请求版本的接口，版本号是通过其他请求接口得到的，对于这种情况，setRequestUrl也必须要求我们设置一个值（实际上没意义），建议可以给它设置一个默认值，不需要请求的时候我们就无需设置了，也更精简一些。

还有再提一个建议：在显示版本更新进度条的时候，建议加一个取消按钮，当下载到一半的时候也可以点击取消下载。

**Comment by Aarondue** [comment]
在实际项目中，apk的url地址以及版本号往往都是通过一个请求接口获得的，而不是分两个接口分别请求，所以觉得setRequestUrl这个有点鸡肋，demo中涉及到网络请求的只需要有apk下载就够了

**Comment by Aarondue** [comment]
特别是一个请求协议，除了返回url，版本号，还返回其他字段用于activity的数据显示。如果按你这种做法的话，所有返回数据是在service中取到的。。。实现起来不太好办。

**Comment by AlexLiuSheng** [comment]
1.你还是没懂requestUrl和downloadUrl的意思，库是通过requestUrl请求版本接口，然后通常来说服务器会返回服务端的版本号和相应的下载链接（downloadUrl），只是你需要在onResponse里面解析数据，所以没有要两个接口。
2.如果想传参数，在showVersionDialog有一个重载方法允许你传入一个Bundle对象。然后在自定义的VersionDialogActivity里面取出来就行了

**Comment by Aarondue** [comment]
在显示版本更新进度条的时候，建议加一个取消按钮，当下载到一半的时候也可以点击取消下载。
