### ISSUE TITLE
vivoY66不能弹窗。会崩溃

### ISSUE THREAD

**Issue by etenel** [AlexLiuSheng/CheckVersionLib#41]
Caused by: Android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**Comment by AlexLiuSheng** [comment]
哪个版本？我加了这个flag的 ，是什么情况会出现

**Comment by etenel** [comment]
1.66的。一会我更新试一下。就是进入主界面要弹出来你那个升级窗口的。我看源码，你在showVersionDialog方法里面直接startActivity(new Intent(this,PermissionDialogActivity.class));的。
我在自定义service里面的onResponses调用的showVersionDialog方法。

**Comment by AlexLiuSheng** [comment]
1.67已经加了

**Comment by etenel** [comment]
可以了。就是每次进入都会重新下载，无论是否之前下载过。

**Comment by AlexLiuSheng** [comment]
你下载的包名和当前app的包名一样不？
然后下载的apk的版本号必须与当前运行的版本号不一样哦

**Comment by etenel** [comment]
都一样。版本号不一样，。是静默下载好后弹出对话框，取消不升级。退出后再进来还是会静默下载，不是直接安装下载好的安装包

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.7.7'
