### ISSUE TITLE
弹出更新对话框后，点击“确定”或者“取消”时会有一闪而过的痕迹。。。

### ISSUE THREAD

**Issue by ghost** [AlexLiuSheng/CheckVersionLib#43]
弹出更新对话框后，点击“确定”或者“取消”时会有一闪而过的痕迹。。。这应该是退出activity的动画效果，不过也很影响用户体验的，可以优化下么

**Comment by mouxuefei** [comment]
这个我感觉可以自定义activity的theme来解决啊,<item name="android:windowAnimationStyle">@null</item>

**Comment by mouxuefei** [comment]
这个我刚觉可以通过自定义Activity的theme来解决啊,`<item name="android:windowAnimationStyle">@null</item>`

**Comment by Aarondue** [comment]
恩恩，我刚才设置了一下沉浸式，让状态栏透明，看起来不明显了。不多我还是觉得首先去请求版本号显得多余，好多时候我们都是已经有了版本号以及url只需要下载apk就行了。特别是一个协议中除了包括版本号还有其他数据，这种方式就局限了。我项目中使用了你的开源库，但是源码改动挺大的。

**Comment by Aarondue** [comment]
我改动代码之后使用方式如下（我直接可以传入线程的downUrl即可，不需要请求后得到）：
        VersionParams.Builder builder = new VersionParams.Builder()
                .setService(VersionUpdateService.class)
                .setCustomDownloadActivityClass(CustomDialogActivity.class)
                .setDownloadUrl(RetrofitClient.URL + entity.getCurVerUrl())
                .setForceUpdate(forceUpdate)
                .setTitle("更新内容")
                .setUpdateMsg(entity.getUpdateInfo())
                .setPositiveText("立即更新")
                .setNegativeText(negativeText);
        AllenChecker.startVersionCheck(mContext, builder.build());

我在VersionParams中增加了downloadUrl 、title 等属性，这样在AVersionService和VersionDialogActivity中只需要传一个参数（VersionParams）就可以，岂不更方面。
    public void showVersionDialog(String downloadUrl, String title, String updateMsg, Bundle paramBundle) {
        this.downloadUrl = downloadUrl;
        this.title = title;
        this.updateMsg = updateMsg;
        this.paramBundle = paramBundle;
        if (versionParams.isSilentDownload()) {
            BroadcastReceiver receiver=new VersionBroadCastReceiver();
            IntentFilter intentFilter=new IntentFilter(PERMISSION_ACTION);
            registerReceiver(receiver,intentFilter);
            Intent intent=new Intent(this,PermissionDialogActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(intent);
        } else {
            goToVersionDialog();
        }
    }

**Comment by Aarondue** [comment]
我改动代码之后使用方式如下（我直接可以传入现成的downUrl即可，使用之前判断版本号）：
VersionParams.Builder builder = new VersionParams.Builder()
.setService(VersionUpdateService.class)
.setCustomDownloadActivityClass(CustomDialogActivity.class)
.setDownloadUrl(RetrofitClient.URL + entity.getCurVerUrl())
.setForceUpdate(forceUpdate)
.setTitle("更新内容")
.setUpdateMsg(entity.getUpdateInfo())
.setPositiveText("立即更新")
.setNegativeText(negativeText);
AllenChecker.startVersionCheck(mContext, builder.build());

我在VersionParams中增加了downloadUrl 、title 等属性，这样在AVersionService和VersionDialogActivity中只需要传一个参数（VersionParams）就可以，岂不更方面。
public void showVersionDialog(String downloadUrl, String title, String updateMsg, Bundle paramBundle) {
this.downloadUrl = downloadUrl;
this.title = title;
this.updateMsg = updateMsg;
this.paramBundle = paramBundle;
if (versionParams.isSilentDownload()) {
BroadcastReceiver receiver=new VersionBroadCastReceiver();
IntentFilter intentFilter=new IntentFilter(PERMISSION_ACTION);
registerReceiver(receiver,intentFilter);
Intent intent=new Intent(this,PermissionDialogActivity.class);
intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
startActivity(intent);
} else {
goToVersionDialog();
}
}

**Comment by AlexLiuSheng** [comment]
谢谢你的意见，我抽空会改进的

**Comment by KevinDue** [comment]
热烈期待下个版本。。。

**Comment by AlexLiuSheng** [comment]
1.6.9
