### ISSUE TITLE
老铁，为什么我的自定义的dialog，每次弹出来都是浮动在在一个新界面（activity），

### ISSUE THREAD

**Issue by 6781287** [AlexLiuSheng/CheckVersionLib#48]
而不是像demo一样浮动在原来的界面

重写的showVersionDialog()方法，用了
versionDialog.setContentView(R.layout.activity_version_update_dialog);

**Comment by 6781287** [comment]
然后今天发现，只要builder设置CustomDownloadActivityClass（MyVersionUpdateDialogActivity.class）时，即使MyVersionUpdateDialogActivity 仅继承VersionDialogActivity，其他内容为空时，也会出现这个问题。

**Comment by AlexLiuSheng** [comment]
设置activity Theme

**Comment by 6781287** [comment]
设置过了
一套用了网上的常用的透明theme，不行
另一套用了你的的basedialog theme也不行

**Comment by AlexLiuSheng** [comment]
你的MyVersionUpdateDialogActivity 设置了android:theme="@style/versionCheckLibvtransparentTheme"没有

**Comment by 6781287** [comment]
设置过，但一设置就报错 Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.


 <style name="activity_version_update_dialog" parent="android:style/Theme.Dialog">
        
        <item name="android:windowBackground">@android:color/transparent</item>
        
        <item name="android:windowNoTitle">true</item>
        
        <item name="android:windowFrame">@null</item>
        
        <item name="android:windowIsFloating">true</item>
        
        <item name="android:backgroundDimEnabled">false</item>
    </style>

    <style name="BaseDialog" parent="android:Theme.Light">
        <item name="android:windowFrame">@null</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:windowIsFloating">true</item>
        <item name="android:windowContentOverlay">@null</item>

    </style>

这俩style都不可以

**Comment by 6781287** [comment]
<style name="activity_version_update_dialog" parent="android:style/Theme.Dialog">
        <item name="android:windowFrame">@null</item>
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowIsFloating">true</item>
        <item name="android:backgroundDimEnabled">false</item>
   </style>

**Comment by AlexLiuSheng** [comment]
android:theme="@style/versionCheckLibvtransparentTheme" 老铁库自带就有个

**Comment by AlexLiuSheng** [comment]
`android:theme="@style/versionCheckLibvtransparentTheme"`

**Comment by 6781287** [comment]
@AlexLiuSheng扎心了老铁，已解决
:joy:thinks
