### ISSUE TITLE
两个APP同时使用了这个依赖，无法同时安装在一台设备中

### ISSUE THREAD

**Issue by Likarl** [AlexLiuSheng/CheckVersionLib#5]
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.zhuan.duoladriver-1: Can't install because provider name com.allenliu.versionchecklib.versionProvider (in package com.zhuan.duoladriver) is already used by com.XXX]

**Comment by AlexLiuSheng** [comment]
使用最新的1.0.3 compile 'com.allenliu.versionchecklib:library:1.0.3'

**Comment by AlexLiuSheng** [comment]
1.0.4

**Comment by Likarl** [comment]
使用的就是1.0.3版本，跟使用了同样的provider有关系，导致无法安装

**Comment by AlexLiuSheng** [comment]
由于适配了androidN 所以使用到了FileProvider  你那个冲突，之前已经解决了，按理来说不会在出现这个问题了。
请问是你另外依赖的库（` is already used by com.XXX]`包名具体是什么）和本库的冲突 还是当前项目与本库的冲突
如果是当前项目可以试着在application里加上
tools:replace="android:authorities"

**Comment by Likarl** [comment]
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.zhuan.duoladriver-1: Can't install because provider name com.allenliu.versionchecklib.versionProvider (in package com.zhuan.duoladriver) is already used by com.zhuan.duola_tong]

**Comment by AlexLiuSheng** [comment]
`compile 'com.allenliu.versionchecklib:library:1.0.4'` 解决了

**Comment by AlexLiuSheng** [comment]
`compile 'com.allenliu.versionchecklib:library:1.0.4'` 解决了
