### ISSUE TITLE
设置静默下载是自动下载完apk才弹出dialog的

### ISSUE THREAD

**Issue by rainiesyg** [AlexLiuSheng/CheckVersionLib#51]
设置静默下载是自动下载完apk才弹出dialog的,为什么不是先弹出dialog,用户点击确定后再开始静默下载并安装,,这样相当于强制下载apk啊

**Comment by AlexLiuSheng** [comment]
参考网易云 豌豆荚这些app的下载模式，wifi模式下开始静默下载

**Comment by rainiesyg** [comment]
静默下载弹出dialog后点击取消,下次打开APP还是会再次下载一遍,怎么办,大神介意加你QQ吗,我的63857574

**Comment by rainiesyg** [comment]
WiFi模式和流量模式都是会重新下载的

**Comment by AlexLiuSheng** [comment]
保证下载包名和运行app包名一致
