### ISSUE TITLE
RequestUrl后端需返回什么格式数据

### ISSUE THREAD

**Issue by shoutleafy** [AlexLiuSheng/CheckVersionLib#54]
您好：
请问RequestUrl后端需返回什么格式数据，直接打印一个int值吗？

**Comment by AlexLiuSheng** [comment]
看你的需求啊 通常版本请求的流程是：先请求服务器数据->解析数据判断版本号和apk下载地址->升级。所以返回的数据通常是服务端的版本号和下载地址
