### ISSUE TITLE
下载功能,在夜神,51模拟器上一直下载不成功

### ISSUE THREAD

**Issue by AndroidFlyMing** [AlexLiuSheng/CheckVersionLib#55]

**Comment by AlexLiuSheng** [comment]
能看看下载代码？

**Comment by AndroidFlyMing** [comment]
dependencies,我只是传了一个url,真机上可以下载,模拟器上不行,我看了下DownloadManager,okhttp是不是不支持模拟器的下载,一般模拟器的版本系统都比较低,是4.2的

**Comment by AndroidFlyMing** [comment]
我明白了,是url是https的,低版本的系统使用okkhttp不支持https连接地址的下载,老铁,怎么解决https是在低版本的 下载

**Comment by AlexLiuSheng** [comment]
给我个https下载链接 我测试加上

**Comment by AlexLiuSheng** [comment]
`compile 'com.allenliu.versionchecklib:library:1.7.2'`
