### ISSUE TITLE
下载过程不能取消下载

### ISSUE THREAD

**Issue by KevinDue** [AlexLiuSheng/CheckVersionLib#56]
建议下载进度条中增加一个取消下载的按钮，点击按钮就取消下载，这样体验性更好。
可以将以下的网络请求逻辑封装一层，增加取消网络请求接口。

AllenHttp.getHttpClient().newCall(request).enqueue(new FileCallBack(versionParams.getDownloadAPKPath(), context.getString(R.string.versionchecklib_download_apkname, context.getPackageName())) {
            @Override
            public void onSuccess(File file, Call call, Response response) {
                listener.onCheckerDownloadSuccess(file);
                Intent i = new Intent(Intent.ACTION_VIEW);
                Uri uri;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    uri = VersionFileProvider.getUriForFile(context, context.getPackageName() + ".versionProvider", file);
                    ALog.e(context.getPackageName() + "");
                    i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                } else {
                    uri = Uri.fromFile(file);
                }
                ALog.e("APK download Success");
                //设置intent的类型
                i.setDataAndType(uri,
                        "application/vnd.android.package-archive");
                PendingIntent pendingIntent = PendingIntent.getActivity(context, 0, i, 0);
                builder.setContentIntent(pendingIntent);
                builder.setContentText(context.getString(R.string.versionchecklib_download_finish));
                builder.setProgress(100, 100, false);
                manager.notify(0, builder.build());
                AppUtils.installApk(context, file);
                if (context instanceof Activity) {
                    ((Activity) context).finish();
                }
            }

            @Override
            public void onDownloading(int progress) {
                ALog.e("downloadProgress:" + progress + "");
                int currentProgress = progress;
//                showLoadingDialog(currentProgress);
                listener.onCheckerDownloading(currentProgress);
                if (currentProgress - lastProgress >= 5) {
                    lastProgress = currentProgress;
                    builder.setContentText(String.format(context.getString(R.string.versionchecklib_download_progress), lastProgress));
                    builder.setProgress(100, lastProgress, false);
                    manager.notify(0, builder.build());
                }
            }

            @Override
            public void onDownloadFailed() {
                Intent intent = new Intent(context, versionParams.getCustomDownloadActivityClass());
                intent.putExtra("isRetry", true);
                intent.putExtra(AVersionService.VERSION_PARAMS_KEY, versionParams);
                PendingIntent pendingIntent = PendingIntent.getActivity(context, 0, intent, FLAG_UPDATE_CURRENT);
                builder.setContentIntent(pendingIntent);
                builder.setContentText(context.getString(R.string.versionchecklib_download_fail));
                builder.setProgress(100, 0, false);
                manager.notify(0, builder.build());
                ALog.e("file download failed");
//                showFailDialog();
                listener.onCheckerDownloadFail();

            }
        });
    }

**Comment by AlexLiuSheng** [comment]
V1版停止维护
