### ISSUE TITLE
class not found when unmarshalling

### ISSUE THREAD

**Issue by zuiguangyin1993** [AlexLiuSheng/CheckVersionLib#59]
![qq 20171106161716](https://user-images.githubusercontent.com/33415238/32432673-671be8ca-c313-11e7-9e9d-ce4987709182.png)
2.设置在通知栏下载，界面上的下载对话框会一闪而过，可否修改一下，谢谢！

**Comment by AlexLiuSheng** [comment]
exception是怎么操作出现的，在我这边复现不了呢。第二个已经解决

**Comment by zuiguangyin1993** [comment]
在service中 调用onResponses(final AVersionService service, String response) 后 但是没影响运行

**Comment by AlexLiuSheng** [comment]
`compile 'com.allenliu.versionchecklib:library:1.7.3'`第一个问题我在看下

**Comment by zuiguangyin1993** [comment]
谢谢！

**Comment by AlexLiuSheng** [comment]
V1版停止维护
