### ISSUE TITLE
7.0以上下载不了问题

### ISSUE THREAD

**Issue by daiwenbing** [AlexLiuSheng/CheckVersionLib#61]
我之前是1.3的最近发包时发现小米7.0检测更新有问题下载失败     我又把依赖改为1.7.6的发现小米华为还是下载不了   点击确定按钮直接什么都没了 不提示 。

**Comment by AlexLiuSheng** [comment]
贴一下你怎么设置VersionParam的

**Comment by daiwenbing** [comment]
/**
     * 检测更新
     */
    public void check_updateapp(){
        CustomVersionDialogActivity.customVersionDialogIndex = 2;
        CustomVersionDialogActivity.isCustomDownloading=true;
        VersionParams.Builder builder=new VersionParams.Builder()
                .setRequestUrl(DSLConnections.APP_ULR)
                .setService(DownLoadAppService.class)
                .setCustomDownloadActivityClass(CustomVersionDialogActivity.class);
        AllenChecker.startVersionCheck(MainActivity.this, builder.build());
    }

**Comment by AlexLiuSheng** [comment]
你看下点击确定之后控制台有没有报错之类的。
还有自定义界面的时候，重写showLoadingDialog里面记得用父类的loadingDialog来实例化，文档已经跟1.3的不一样了

**Comment by AlexLiuSheng** [comment]
你可以下载demo再看下

**Comment by daiwenbing** [comment]
现在OK了修改后代码如下   
1.不足就是权限问题   如果点击拒绝了下次就不会有授权限弹窗提示了  


  /**
     * 检测更新
     */
    public void check_updateapp(){
        CustomVersionDialogActivity.customVersionDialogIndex = 2;
//        CustomVersionDialogActivity.isCustomDownloading=true;
        VersionParams.Builder builder=new VersionParams.Builder()
                .setRequestUrl(DSLConnections.APP_ULR)
                .setService(DownLoadAppService.class)
                .setShowDownloadingDialog(false)
                .setCustomDownloadActivityClass(CustomVersionDialogActivity.class);
        AllenChecker.startVersionCheck(MainActivity.this, builder.build());
    }


      if (!TextUtils.isEmpty(info.getData().getUrl())){
                 /*       boolean isForceUpdate=true;
                        Bundle bundle=new Bundle();
                        bundle.putBoolean("isForceUpdate",isForceUpdate);
                        service.showVersionDialog(info.getData().getUrl(), "检测到新版本请及时更新",info.getData().getDescription(),bundle);*/
                        service.showVersionDialog(info.getData().getUrl(), "检测到新版本请及时更新",info.getData().getDescription());
                    }


    /**
     * 要更改下载中界面 只需要重写此方法即可
     * 因为下载的时候会不断回调此方法
     * dialog使用全局 只初始化一次
     * 使用父类的loadingDialog保证下载成功会dimiss掉dialog
     *
     * @param currentProgress
     */
    @Override
    public void showLoadingDialog(int currentProgress) {
            finish();
/*        if (!isCustomDownloading) {
            super.showLoadingDialog(currentProgress);
        } else {
            //使用父类的loadingDialog保证下载成功会dimiss掉dialog
            if (loadingDialog == null) {
                loadingView = LayoutInflater.from(this).inflate(R.layout.custom_download_layout, null);
                loadingDialog = new AlertDialog.Builder(this).setTitle("").setView(loadingView).create();
                loadingDialog.setCancelable(false);
                loadingDialog.setCanceledOnTouchOutside(false);
                loadingDialog.setOnCancelListener(new DialogInterface.OnCancelListener() {
                    @Override
                    public void onCancel(DialogInterface dialog) {
                        finish();

                    }
                });
            }
            ProgressBar pb = (ProgressBar) loadingView.findViewById(R.id.pb);
            TextView tvProgress = (TextView) loadingView.findViewById(R.id.tv_progress);
            tvProgress.setText(String.format(getString(R.string.versionchecklib_progress), currentProgress));
            pb.setProgress(currentProgress);
            loadingDialog.show();
        }*/
//        Toast.makeText(this, "显示自定义的下载加载框", Toast.LENGTH_SHORT).show();
    }

**Comment by AlexLiuSheng** [comment]
不会啊！你只要没有电never ask again 拒绝了下次也会请求权限的

**Comment by daiwenbing** [comment]
这个好像是在有的小米手机上会是这样  不是全部
