### ISSUE TITLE
下载完成后，没有点击安装， 下次执行 检查更新请求还是重新下载一遍！！！

### ISSUE THREAD

**Issue by 897902334** [AlexLiuSheng/CheckVersionLib#62]
我用demo测试下载完成后，跳转到安装APK的界面后，我没有点击安装，返回demo， 再次执行 检查更新请求还是重新下载一遍！！！   而且 我集成到了我自己的项目中，也是同样的情况，并且看了你的文档说是 本地安装包的报名和安装好的包名一致并且版本小于安装包的   这些都成立啊  还是重新下载，  而且demo中 有个问题  偶尔不用重新下载了 但是会出现 解析包出现异常的情况！！！   麻烦修复一下  这个bug好难受啊！

**Comment by AlexLiuSheng** [comment]
朋友你先用下，这是一个bug我下周来看下

**Comment by 897902334** [comment]
@AlexLiuSheng   多谢回复，  还有个问题  我没搞明白，  就是  静默更新，  比如我在主界面执行了静默更新的代码了， 然后此时用户到了其他界面做某事了，  就在这个时候 静默更新完成了，  那个更新框弹出来了，这样体验很不好吧，  比如用户正在看视频呢  此时弹出一个更新框  总是感觉不够有好，   我想的是 等他回到主界面  我在onRestart调用这更新方法，此时也就下载完了  提示用户直接安装即可，这样就遇到这个重新下载的问题了  ···  一直是个死循环 下载不完了  哈哈··     希望你修改修改  暂时就不用这个静默了  等你修复好了再用吧！  谢谢。

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.7.7'

**Comment by hejie** [comment]
还发现一个逻辑问题
在注释这里  “ //判断安装包存在并且包名一样并且版本号不一样”
 if (info != null && context.getPackageName().equalsIgnoreCase(info.packageName) && context.getPackageManager().getPackageInfo(context.getPackageName(), 0).versionCode != info.versionCode) {
                   //判断开发者传入的最新版本号是否大于缓存包的版本号，大于那么相当于没有缓存
                    if (newestVersionCode != null && info.versionCode < newestVersionCode) {
                        result = false;
                    } else
                        result = true;

                }
如果versionCode一样，最终 result 应该返回true，就是走缓存呀，但你这里是返回false 
而外面的逻辑又说使用缓存，这里前后矛盾
 if (DownloadManager.checkAPKIsExists(getApplicationContext(), downloadPath,builder.getNewestVersionCode()) && !builder.isForceRedownload()) {
            ALog.e("using cache");
            install();
            return;
        }
