### ISSUE TITLE
app 会覆盖app名字？

### ISSUE THREAD

**Issue by whyyao** [AlexLiuSheng/CheckVersionLib#65]
只要把库加进gradle就会覆盖app本身名字？请问应该怎么取消自动覆盖呢

**Comment by AlexLiuSheng** [comment]
不会啊，默认是你自己app的名字覆盖库的名字

**Comment by 18710891669** [comment]
@whyyao  覆盖应用名称这个问题最后可以了吗？   我在小米mix2  api25测试会覆盖   低版本没问题
