### ISSUE TITLE
开启前台通知，取消下载

### ISSUE THREAD

**Issue by Leavds** [AlexLiuSheng/CheckVersionLib#68]
开启前台通知，取消下载，再点击前台通知开启下载，再点击，会出现多个下载dialog，多个下载任务

**Comment by AlexLiuSheng** [comment]
你怎么取消下载的啊

**Comment by Leavds** [comment]
这个是这样的  就是在前台通知 正在下载的时候 或者 停止下载的时候  你点击  ，点一次开启一个dialog下载进度

**Comment by AlexLiuSheng** [comment]
1.7.9
