### ISSUE TITLE
下载文件时，进度数是负数，前台通知栏进度不显示数字，下完了 显示个 下载完成

### ISSUE THREAD

**Issue by Leavds** [AlexLiuSheng/CheckVersionLib#69]

**Comment by AlexLiuSheng** [comment]
贴下VersionParams参数和downloadUrl

**Comment by Leavds** [comment]
参数 就是2.只使用下载模块这个，url这个是 公司的项目 不方便发

**Comment by Leavds** [comment]
是负数 直接就是文件的大小  但是是 负的 ，

**Comment by Leavds** [comment]
在FileCallBack 里 fos.write(buf, 0, len);
                sum += len;
                final int progress = (int) (sum * 1.0f / total * 100);     转换前  打印sum  是正的  ，转换后 打印   progress 就是负的

**Comment by AlexLiuSheng** [comment]
了解了，稍等

**Comment by Leavds** [comment]
11-24 14:33:33.073 8900-9281/? D/ppppp: ppppp3792703
11-24 14:33:33.073 8900-9281/? D/ppppp: progress-379270304
11-24 14:33:33.073 8900-9281/? D/ppppp: ppppp3794665
11-24 14:33:33.073 8900-9281/? D/ppppp: progress-379466496

**Comment by AlexLiuSheng** [comment]
1.7.9试一下

**Comment by Leavds** [comment]
更了  还是有这个问题

**Comment by AlexLiuSheng** [comment]
29949821加我扣扣

**Comment by AlexLiuSheng** [comment]
apk下载路级不是一级

**Comment by smxy34** [comment]
下载出现负数，是什么问题？目前的版本下载进度，也出现了负数

**Comment by smxy34** [comment]
下载路径已经是放在一级路径下了
