### ISSUE TITLE
Demo中的静默更新没有反应！

### ISSUE THREAD

**Issue by 897902334** [AlexLiuSheng/CheckVersionLib#70]
我把demo运行起来 ，试了下静默更新，但是怎么试都没有反应！  其他的都好好的  就是静默更新没有反应，   望作者看看这个问题。  谢谢！

**Comment by AlexLiuSheng** [comment]
没发现这个问题，你看看你是不是最新的code，还有静默下载控制台的log

**Comment by 897902334** [comment]
我又重新下载了一遍demo，  而且 我发现，   第一次我直接尝试使用静默更新，他就没有反应了，  然而我用默认的更新把APK下载到SD中后，  再次尝试使用静默就可以了，  不知道啥情况  你可以试试，  你把本地下载好的apk给删掉，直接用静默试试看看会不会出现跟我一样的情况！ 
第一次安装好，第一次使用静默的log 如下！
![jingmo](https://user-images.githubusercontent.com/9455329/33229674-09cdf712-d20e-11e7-824c-2c97bd07e770.jpg)

**Comment by AlexLiuSheng** [comment]
谢谢指出，我看到这个问题了，稍等我修复一下

**Comment by 897902334** [comment]
嗯嗯，  有个小建议，  就是静默更新下载的时候 不知道你有没有加这个逻辑，  就是WIFI的情况下才会去下载APK， 流量的情况就不下载了，  WIFI情况下 下载完直接提示用户安装即可     有这个逻辑么？

**Comment by AlexLiuSheng** [comment]
最新版修复了，判断wifi这个逻辑你得自己加
