### ISSUE TITLE
强制更新遇到问题了

### ISSUE THREAD

**Issue by ProfessionalMe** [AlexLiuSheng/CheckVersionLib#71]
我设置了强制更新，然后点击确定 就是正在更新，这个时候我点击手机的返回键，这个下载框就关了，等会会提示下载失败 是否重试，然后点击取消的时候  就关闭了dialog  APP还是可以正常使用 强制更新没有了作用，怎么解决

**Comment by AlexLiuSheng** [comment]
你是最新的demo？我昨天改了下

**Comment by ProfessionalMe** [comment]
是啊 我昨天刚用的，怎么解决

**Comment by AlexLiuSheng** [comment]
git pull下看看

**Comment by ProfessionalMe** [comment]
又改回来了？

**Comment by ProfessionalMe** [comment]
我是添加的依赖用的 怎么pull

**Comment by AlexLiuSheng** [comment]
库是没有提供强制更新功能的，你要用请看demo怎么实现的，我以为你用的demo

**Comment by ProfessionalMe** [comment]
好的，

**Comment by AlexLiuSheng** [comment]
有一个专门的强制更新的demo你可以看下

**Comment by ProfessionalMe** [comment]
看了你的demo,如果是强制更新 isForce就是true  然后如果点击取消的时候就直接Finish  我也是按照你这个做的，，然后强制更新的时候 点击确定就是正在下载的对话框，点击返回这个对话框就关闭了，然后我更改了方法，当下载中点击返回的时候 我弹出下载失败的对话框，然后判断是不是强制更新，如果是 点击取消就结束Activity  如果不是 就结束对话框，不知道对不对

**Comment by ProfessionalMe** [comment]
我刚看了你的强制更新的Demo  你测试一下  更新的时候 就是在下载进度框那个界面  你点击返回试试，进度框就关了  然后后边就没了  就是说强制更新每起到作用

**Comment by ProfessionalMe** [comment]
问一下 正在下载的对话框怎么关闭，

**Comment by AlexLiuSheng** [comment]
ForceUpdateDemo?那个compile的版本不是最新的 ，试试最新的呢

**Comment by ProfessionalMe** [comment]
可以留一下联系方式吗

**Comment by AlexLiuSheng** [comment]
29949821

**Comment by AlexLiuSheng** [comment]
库版本引入错误
