### ISSUE TITLE
吓我一跳  最新版1.8.2  库名覆盖应用名了  小米mix2

### ISSUE THREAD

**Issue by 18710891669** [AlexLiuSheng/CheckVersionLib#72]

**Comment by AlexLiuSheng** [comment]
`tools:replace="android:icon, android:label"`

**Comment by 18710891669** [comment]
加在application节点下？

**Comment by 18710891669** [comment]
设置了替换运行后还是不行  api25以上测试  就会出现覆盖 低版本系统没问题

**Comment by AlexLiuSheng** [comment]
同样是25 没出现你这个问题啊 你看看其他25的手机有没有这个问题

**Comment by 18710891669** [comment]
tools:replace="android:icon, android:label"  你不加这个替换会不会出现覆盖？

**Comment by AlexLiuSheng** [comment]
你不加默认就会替换库的资源，我没加

**Comment by AlexLiuSheng** [comment]
你新建一个项目试试 导入库试试会不会覆盖

**Comment by 18710891669** [comment]
好吧  我再看看，3Q
