### ISSUE TITLE
下载中点返回键有问题

### ISSUE THREAD

**Issue by hzq19920817** [AlexLiuSheng/CheckVersionLib#73]
如果下载中点击返回键弹出下载失败是否重试，选择取消，但是还需要再点击一次返回键屏幕才能监听到事件

**Comment by AlexLiuSheng** [comment]
版本多少

**Comment by hzq19920817** [comment]
最新的版本

**Comment by AlexLiuSheng** [comment]
`还需要再点击一次返回键屏幕才能监听到事件` 你是说你在监听事件的时候 出现的问题么 还是说点两次才能取消

**Comment by hzq19920817** [comment]
就是屏幕上是没有选择框了，但是屏幕不能点击，要再一次点击返回键才能点，应该是activity（下载的）虽然看不见但是没有关掉

**Comment by AlexLiuSheng** [comment]
好的

**Comment by AlexLiuSheng** [comment]
1.8.3
