### ISSUE TITLE
8.0适配问题

### ISSUE THREAD

**Issue by XuQK** [AlexLiuSheng/CheckVersionLib#80]
机型：pixel一代
系统版本：8.0
库版本：1.8.4
问题：使用通知栏下载的时候，每一次更新下载进度都会有系统提示，会不停的有提示音和振动。
另外，可否提供一个开关，在使用dialog显示下载进度时，返回键直接取消。现在的情况是返回键后会弹个下载失败，询问是否重复下载的dialog。

**Comment by chendabai** [comment]
我是 使用 V 1.8.3 版本后震动消失,,,,先回退吧

**Comment by AlexLiuSheng** [comment]
感谢指出bug    1.8.6已修复 多加了一个开关 `setShowDownloadFailDialog`

**Comment by Destiny01** [comment]
机型：华为v10
系统版本：8.0
库版本：1.8.6
问题：使用通知栏下载的时候，每一次更新下载进度都会有系统提示，会不停的有提示音和振动。

**Comment by 317056658** [comment]
Error:Could not find com.android.support:appcompat-v7:27.0.0.   为什么要下载这个包 才能添加 版本库1.8.6？    不向下兼容吗？
