### ISSUE TITLE
1.8.4更新之后就一直提示27.0.0的问题

### ISSUE THREAD

**Issue by hzq19920817** [AlexLiuSheng/CheckVersionLib#81]
建议低版本的也能用，就是support25.0.0之类的，因为官方27.0.0有些API做了修改手势冲突

**Comment by tiann** [comment]
+1

**Comment by BestRockyMen** [comment]
+1

**Comment by hxw319726** [comment]
楼主是否可以参考http://blog.csdn.net/yuzhiqiang_1993/article/details/78214812，去除support依赖

**Comment by AlexLiuSheng** [comment]
不维护1.+
