### ISSUE TITLE
app的名字无法正常显示了 ，一直显示的是  VersionCheckLib

### ISSUE THREAD

**Issue by lfxwoaini** [AlexLiuSheng/CheckVersionLib#83]
怎么回事，解答？？？

**Comment by 18710891669** [comment]
你是哪个版本库？

**Comment by lfxwoaini** [comment]
1.8.4, 是value-en影响了  android:label="@string/app_name" ，导致显示在桌面的app名字不正确

**Comment by AlexLiuSheng** [comment]
1.8.6开始不会影响了，1.8.6之前需要自己在value-en 里面string 定义一下appname
