### ISSUE TITLE
下载的进度条数据显示不正常

### ISSUE THREAD

**Issue by xcode126** [AlexLiuSheng/CheckVersionLib#84]
下载的进度条数据显示不正常，本应该显示：“50%”这种样式，但是显示的是“-4023222%”，请问是什么原因造成的，我换成其他apk下载地址显示正常，感觉应该给apk大小有关系。

**Comment by AlexLiuSheng** [comment]
应该给你下载链接有关，apk下载地址应该不是直接指向文件的地址，导致拿不到content-length
