### ISSUE TITLE
8.0提示音问题？

### ISSUE THREAD

**Issue by Destiny01** [AlexLiuSheng/CheckVersionLib#85]
机型：华为荣耀v10
系统版本：8.0
库版本：1.8.6
问题：使用通知栏下载的时候，每一次更新下载进度都会有系统提示，会不停的有提示音和振动。

**Comment by AlexLiuSheng** [comment]
1.8.7解决了，android O 上的通知设置跟之前的不一样，而且一旦设置了通知优先级 ，后面再用代码设置会没用，必须要卸载重新安装才行。所以用最新版之后，把app重新安装测试即可
参考
`https://stackoverflow.com/questions/45919392/disable-sound-from-notificationchannel`

**Comment by AlexLiuSheng** [comment]
V1版停止维护
