### ISSUE TITLE
下载的apk名称如何改变？

### ISSUE THREAD

**Issue by Lindroy** [AlexLiuSheng/CheckVersionLib#86]
写了一个Demo，发现下载下来的apk名称就是Demo的包名，虽然说没什么影响，但希望还是能够保留原来的apk名称或者可以修改为好。

**Comment by AlexLiuSheng** [comment]
这个库暂时没有提供修改的方法，默认名是包名

**Comment by lovesdash** [comment]
老铁，这个地方选择包名做文件名是有问题的。举个栗子，假设开启了从缓存拿数据，包名（com.a.b）1.0.0检测到1.0.1，当把1.0.1下载到本地后，当1.0.1检测更新1.0.2时，1.0.1每次需要下载1.0.2文件时发现本地已经有个com.a.b这个文件，就不会下载1.0.2，直接将1.0.1文件当作新版本文件，进行覆盖安装，那么程序就一直进行循环更新。

**Comment by AlexLiuSheng** [comment]
z
