### ISSUE TITLE
安装 1.8.7

### ISSUE THREAD

**Issue by 317056658** [AlexLiuSheng/CheckVersionLib#87]
报错 找不到 'com.android.support:appcompat-v7:27'     不向下兼容吗  ？

**Comment by AlexLiuSheng** [comment]
```
compile ('com.allenliu.versionchecklib:library:1.8.7'){
        exclude module: "appcompat-v7"

    }
```
使用你自己的v7包

**Comment by 317056658** [comment]
好 谢谢。 可用自定义自己的dialogActivity？ 因为我觉得把activity写成dialog  扩张性更强

**Comment by AlexLiuSheng** [comment]
可以自定义,你看文档

**Comment by 317056658** [comment]
报错：Error:Execution failed for task ':myapplicationkukai:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs  
添加compile ('com.allenliu.versionchecklib:library:1.8.7'){
        exclude module: "appcompat-v7"
    }

**Comment by AlexLiuSheng** [comment]
你targetVersion BuildToolVersion 和自己的v7包统一不

**Comment by 317056658** [comment]
targetVersion   
BuildToolVersion     都是25  为什么不统一？

**Comment by 317056658** [comment]
compile 'com.android.support:recyclerview-v7:25.3.1'  这是我的包

**Comment by AlexLiuSheng** [comment]
我说appcompat-v7包

**Comment by AlexLiuSheng** [comment]
你导入一个相应版本的appcmpat-v7包就行了

**Comment by 317056658** [comment]
compile 'com.android.support:appcompat-v7:25.3.1'   这是我的v7包

**Comment by AlexLiuSheng** [comment]
贴一下你的gradle代码 我看看

**Comment by 317056658** [comment]
compileSdkVersion 25
    buildToolsVersion "25.0.0"
    aaptOptions.cruncherEnabled = false
    aaptOptions.useNewCruncher = false
    defaultConfig {
        applicationId "com.kkkcut.www.myapplicationkukai"
        minSdkVersion 21  //17
        targetSdkVersion 25
        versionCode 2
        versionName "3.0.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [eventBusIndex: 'com.bandeng.MyEventBusIndex']
            }
        }

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}
repositories {
    flatDir { dirs 'libs' }
}

//apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'com.neenbedankt.android-apt'
apt {
    arguments {
        eventBusIndex "com.bandeng.MyEventBusIndex"
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile(name: 'sliding_menu_lib', ext: 'aar')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.google.android.gms:play-services-appindexing:8.4.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.31'
    testCompile 'junit:junit:4.12'
    apt 'org.greenrobot:eventbus-annotation-processor:3.0.1'
    compile 'com.qiangxi.checkupdatelibrary:checkupdatelibrary:1.1.3@aar'
    compile 'com.squareup.okhttp3:okhttp:3.6.0'
    compile 'com.squareup.okio:okio:1.11.0'
    compile 'com.github.franmontiel:PersistentCookieJar:v1.0.1'
    compile ('com.allenliu.versionchecklib:library:1.8.7'){
        exclude module: "appcompat-v7"
    }
}

**Comment by AlexLiuSheng** [comment]
编译的时候报什么错

**Comment by 317056658** [comment]
Error:Execution failed for task ':myapplicationkukai:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by AlexLiuSheng** [comment]
我要看log

**Comment by 317056658** [comment]
这就是错误啊

**Comment by 317056658** [comment]
studio logcat没有报错   Gradle 编译报错。 你这个 库  等你向下兼容好了 我再来吧
