### ISSUE TITLE
我自定义了下载路径，解析包错误

### ISSUE THREAD

**Issue by steven-gao** [AlexLiuSheng/CheckVersionLib#89]
我自定义了下载路径，在7.0系统上，经常报解析包错误，但是我查看apk包文件没问题，点击可安装。大神能给分析下吗？

**Comment by AlexLiuSheng** [comment]
没遇到这个问题，你意思使用默认的路劲就没有问题么

**Comment by steven-gao** [comment]
后来发现跟v2签名有关系，不用v2签名没错。使用了，就经常报这个错误

**Comment by steven-gao** [comment]
我们用7.0的手机下载完经常报解析包错误。请大神帮忙看看吧。具体原因我也找不到

**Comment by steven-gao** [comment]
大神你的FileCallBack.java 源码有段读取文件的代码如下：
`  while ((len = is.read(buf)) != -1) {
                total = response.body().contentLength();
//                ALog.e("file total size:"+total);
                fos.write(buf, 0, len);
                sum += len;
                final int progress = (int) (((double)sum / total) * 100);
                // 下载中
                handler.post(new Runnable() {
                    @Override
                    public void run() {
                        onDownloading(progress);
                    }
                });

            }`
为什么 total取值放在while循环里面，一般都放外面吧？
