### ISSUE TITLE
setRequestUrl和showVersionDialog里面的url有什么区别吗

### ISSUE THREAD

**Issue by tank21** [AlexLiuSheng/CheckVersionLib#9]
setRequestUrl和showVersionDialog里面的url有什么区别吗

**Comment by AlexLiuSheng** [comment]
setRequestUrl 是你接口请求的地址
showVersionDialog传入的url 是apk下载地址

**Comment by tank21** [comment]
接口请求下来的数据，respone怎么获取呢

**Comment by AlexLiuSheng** [comment]
看readme，需要你自己解析接口返回的数据  自定义一个继承AVersionService的service 然后重写onResponses

**Comment by tank21** [comment]
怎么每次都是弹出下载失败是否重试呢

**Comment by tank21** [comment]
demo的下载也不行的，每次都是提示下载失败请重试

**Comment by AlexLiuSheng** [comment]
demo 里面的下载地址应该失效了 你自己弄个apk下载地址进去试试

**Comment by tank21** [comment]
一样的，demo的APK地址用浏览器也可以下载的

**Comment by AlexLiuSheng** [comment]
才看到，请问你什么机型啊，我这里都是好的啊

**Comment by tank21** [comment]
失败的原因是没有开启权限，希望在弹窗后加个权限判断

**Comment by AlexLiuSheng** [comment]
读写文件的权限么？

**Comment by tank21** [comment]
是的
