### ISSUE TITLE
大神，你的下载进度有问题

### ISSUE THREAD

**Issue by steven-gao** [AlexLiuSheng/CheckVersionLib#90]
我用到了你的框架，首先表示感谢。
其次我发现了一个问题，
使用这个下载链接测试 http://pxapp.puxinasset.com/3.0-puxinasset_300_jiagu_sign.apk?attname=
发现进度会时大时小。必现

**Comment by AlexLiuSheng** [comment]
进度时大时小是什么意思

**Comment by steven-gao** [comment]
你代码没问题
