### ISSUE TITLE
在系统安装界面（PackageInstallerActivity）取消安装之后可能会卡在闪屏页

### ISSUE THREAD

**Issue by Lindroy** [AlexLiuSheng/CheckVersionLib#91]
用户启动应用时会在闪屏页提示更新，用户下载好apk后会跳转到系统的安装界面（PackageInstallerActivity），如果这时候用户点击“取消”不继续安装，PackageInstallerActivity就会销毁，但是回到本应用时会停留在闪屏页，必须按返回键才能完全退出完全退出应用。有没有办法可以监听到用户在PackageInstallerActivity点击按钮的操作？这样方便我们退出应用（强制更新时）或者进入应用。

**Comment by AlexLiuSheng** [comment]
没法，一般的是做法是在进入PackageInstallerActivity的时候就关闭应用了

**Comment by Lindroy** [comment]
进入PackageInstallerActivity的时候就关闭应用？就是说安装的时候关闭旧版本的应用吗？这样也可以的，但是如何关闭呢？

**Comment by AlexLiuSheng** [comment]
你看库有个强制更新的demo，监听事件
```
 setApkDownloadListener(this);
 setDialogDimissListener(this);
```
https://github.com/AlexLiuSheng/CheckVersionLib/blob/master/ForceUpdateDemo/app/src/main/java/com/allenliu/forceupdatedemo/CustomDialogActivity.java

**Comment by Lindroy** [comment]
哦，我强制更新的界面跟你原生的不一样，强制更新时我只设置一个确定按钮，用户必须点击“确定”去下载apk。不过我有思路了，可以在下载成功之后就把应用销毁。另外，我还遇到一个奇怪的问题，就是setDialogDimissListener不起作用，不知道为什么……

**Comment by AlexLiuSheng** [comment]
没理由啊，是用我的库自定义界面的？如果是，你看文档的自定义versionDialog

**Comment by Lindroy** [comment]
好的，我看看。

**Comment by Lindroy** [comment]
多谢解答了，秒回啊。
