### ISSUE TITLE
OOM了，是我使用的姿势不对么？

### ISSUE THREAD

**Issue by piao33** [AlexLiuSheng/CheckVersionLib#93]
遇到了“java.lang.OutOfMemoryError: Failed to allocate a 32151660 byte allocation with 16777120 free bytes and 27MB until OOM”，具体报错是“at com.allenliu.versionchecklib.core.AVersionService$1.onResponse(AVersionService.java:89)” 请问是我使用的有问题么？

**Comment by bslml** [comment]
我用leakcanary也发现了内存泄漏。。。

**Comment by AlexLiuSheng** [comment]
我改一下

**Comment by AlexLiuSheng** [comment]
1.8.8 开启的时候传Application。现在自动处理了释放static引用
