### ISSUE TITLE
HTTP协议chunk编码

### ISSUE THREAD

**Issue by leocxl13** [AlexLiuSheng/CheckVersionLib#94]

**Comment by leocxl13** [comment]
HTTP协议chunk编码时，content-length为-1，下载进度有计算有问题

**Comment by AlexLiuSheng** [comment]
chunk 编码不支持哦。因为chunk编码是分段式的压缩包 http header里面也没有content-length，拿不到

**Comment by fxlones** [comment]
就这个问题我想问下，如果我想让检查更新接口返回文件大小，然后再在下载的时候直接用这个值做total该怎么做
