### ISSUE TITLE
没有新版本时该如何处理？

### ISSUE THREAD

**Issue by zhengxiaochuan** [AlexLiuSheng/CheckVersionLib#97]
检查更新一般是两种场景：
第一种就是自动检测版本，比如在进入APP主页面中，当没有新版本时，不需要提示用户没有新版本；
第二种就是在"设置"页面中手动点击进行版本检测，当没有新版本时，可以进行提示用户已经是最新版本；

这两种场景该怎么实现啊使用这个版本检测升级库？

**Comment by AlexLiuSheng** [comment]
使用V2版，你在不同的地方开启版本检测，request 有回调，你可以在里面判断
